import type { MonsterDefinition } from "../monsterTypes";

/**
 * Complete SRD 5.2.1 Aberration catalog.
 *
 * Source: System Reference Document 5.2.1, Monsters A–Z.
 * Licensed under CC BY 4.0.
 */
export const aberrations: MonsterDefinition[] = [
  {
    id: "aboleth",
    name: "Aboleth",
    type: "Aberration",
    size: "Large",
    alignment: "Lawful Evil",
    armorClass: 17,
    hp: 150,
    hitDice: "20d10 + 40",
    initiative: { modifier: 7, score: 17 },
    speed: { walk: 10, swim: 40 },
    stats: { str: 21, dex: 9, con: 15, int: 18, wis: 15, cha: 18 },
    savingThrows: { dex: 3, con: 6, int: 8, wis: 6 },
    skills: { History: 12, Perception: 10 },
    senses: { darkvision: 120, passivePerception: 20 },
    languages: ["Deep Speech", "Telepathy 120 ft."],
    challengeRating: "10",
    xp: 5900,
    proficiencyBonus: 4,
    traits: [
      { name: "Amphibious", text: "The aboleth can breathe air and water." },
      { name: "Eldritch Restoration", text: "If destroyed, the aboleth gains a new body in 5d10 days, reviving with all its Hit Points in the Far Realm or another location chosen by the GM." },
      { name: "Legendary Resistance (3/Day, or 4/Day in Lair)", text: "If the aboleth fails a saving throw, it can choose to succeed instead." },
      { name: "Mucus Cloud", text: "While underwater, the aboleth is surrounded by mucus. Constitution Saving Throw: DC 14, each creature in a 5-foot Emanation originating from the aboleth at the end of the aboleth’s turn. Failure: The target is cursed. Until the curse ends, the target’s skin becomes slimy, the target can breathe air and water, and it can’t regain Hit Points unless it is underwater. While the cursed creature is outside a body of water, the creature takes 6 (1d12) Acid damage at the end of every 10 minutes unless moisture is applied to its skin before those minutes have passed." },
      { name: "Probing Telepathy", text: "If a creature the aboleth can see communicates telepathically with the aboleth, the aboleth learns the creature’s greatest desires." },
    ],
    actions: [
      { name: "Multiattack", text: "The aboleth makes two Tentacle attacks and uses either Consume Memories or Dominate Mind if available." },
      { name: "Tentacle", text: "Melee Attack Roll: +9, reach 15 ft. Hit: 12 (2d6 + 5) Bludgeoning damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 14) from one of four tentacles." },
      { name: "Consume Memories", text: "Intelligence Saving Throw: DC 16, one creature within 30 feet that is Charmed or Grappled by the aboleth. Failure: 10 (3d6) Psychic damage. Success: Half damage. Failure or Success: The aboleth gains the target’s memories if the target is a Humanoid and is reduced to 0 Hit Points by this action." },
      { name: "Dominate Mind (2/Day)", text: "Wisdom Saving Throw: DC 16, one creature the aboleth can see within 30 feet. Failure: The target has the Charmed condition until the aboleth dies or is on a different plane of existence from the target. While Charmed, the target acts as an ally to the aboleth and is under its control while within 60 feet of it. In addition, the aboleth and the target can communicate telepathically with each other over any distance. The target repeats the save whenever it takes damage as well as after every 24 hours it spends at least 1 mile away from the aboleth, ending the effect on itself on a success." },
    ],
    legendaryActions: [
      { name: "Legendary Action Uses: 3 (4 in Lair)", text: "Immediately after another creature’s turn, the aboleth can expend a use to take one of the following actions. The aboleth regains all expended uses at the start of each of its turns." },
      { name: "Lash", text: "The aboleth makes one Tentacle attack." },
      { name: "Psychic Drain", text: "If the aboleth has at least one creature Charmed or Grappled, it uses Consume Memories and regains 5 (1d10) Hit Points." },
    ],
  },
  {
    id: "chuul",
    name: "Chuul",
    type: "Aberration",
    size: "Large",
    alignment: "Chaotic Evil",
    armorClass: 16,
    hp: 76,
    hitDice: "9d10 + 27",
    initiative: { modifier: 0, score: 10 },
    speed: { walk: 30, swim: 30 },
    stats: { str: 19, dex: 10, con: 16, int: 5, wis: 11, cha: 5 },
    skills: { Perception: 4 },
    damageImmunities: ["Poison"],
    conditionImmunities: ["Poisoned"],
    senses: { darkvision: 60, passivePerception: 14 },
    languages: ["Understands Deep Speech but can’t speak"],
    challengeRating: "4",
    xp: 1100,
    proficiencyBonus: 2,
    traits: [
      { name: "Amphibious", text: "The chuul can breathe air and water." },
      { name: "Sense Magic", text: "The chuul senses magic within 120 feet of itself. This trait otherwise works like the Detect Magic spell but isn’t itself magical." },
    ],
    actions: [
      { name: "Multiattack", text: "The chuul makes two Pincer attacks and uses Paralyzing Tentacles." },
      { name: "Pincer", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 9 (1d10 + 4) Bludgeoning damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 14) from one of two pincers." },
      { name: "Paralyzing Tentacles", text: "Constitution Saving Throw: DC 13, one creature Grappled by the chuul. Failure: The target has the Poisoned condition and repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically. While Poisoned, the target has the Paralyzed condition." },
    ],
  },
  {
    id: "cloaker",
    name: "Cloaker",
    type: "Aberration",
    size: "Large",
    alignment: "Chaotic Neutral",
    armorClass: 14,
    hp: 91,
    hitDice: "14d10 + 14",
    initiative: { modifier: 5, score: 15 },
    speed: { walk: 10, fly: 40 },
    stats: { str: 17, dex: 15, con: 12, int: 13, wis: 14, cha: 7 },
    skills: { Stealth: 5 },
    conditionImmunities: ["Frightened"],
    senses: { darkvision: 120, passivePerception: 12 },
    languages: ["Deep Speech", "Undercommon"],
    challengeRating: "8",
    xp: 3900,
    proficiencyBonus: 3,
    traits: [
      { name: "Light Sensitivity", text: "While in Bright Light, the cloaker has Disadvantage on attack rolls." },
    ],
    actions: [
      { name: "Multiattack", text: "The cloaker makes one Attach attack and two Tail attacks." },
      { name: "Attach", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 13 (3d6 + 3) Piercing damage. If the target is a Large or smaller creature, the cloaker attaches to it. While the cloaker is attached, the target has the Blinded condition, and the cloaker can’t make Attach attacks against other targets. In addition, the cloaker halves the damage it takes (round down), and the target takes the same amount of damage. The cloaker can detach itself by spending 5 feet of movement. The target or a creature within 5 feet of it can take an action to try to detach the cloaker, doing so by succeeding on a DC 14 Strength (Athletics) check." },
      { name: "Tail", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 8 (1d10 + 3) Slashing damage." },
    ],
    bonusActions: [
      { name: "Moan", text: "Wisdom Saving Throw: DC 13, each creature in a 60-foot Emanation originating from the cloaker. Failure: The target has the Frightened condition until the end of the cloaker’s next turn. Success: The target is immune to this cloaker’s Moan for the next 24 hours." },
      { name: "Phantasms (Recharge after a Short or Long Rest)", text: "The cloaker casts the Mirror Image spell, requiring no spell components and using Wisdom as the spellcasting ability. The spell ends early if the cloaker starts or ends its turn in Bright Light." },
    ],
  },
  {
    id: "darkmantle",
    name: "Darkmantle",
    type: "Aberration",
    size: "Small",
    alignment: "Unaligned",
    armorClass: 11,
    hp: 22,
    hitDice: "5d6 + 5",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 10, fly: 30 },
    stats: { str: 16, dex: 12, con: 13, int: 2, wis: 10, cha: 5 },
    skills: { Stealth: 3 },
    senses: { blindsight: 60, passivePerception: 10 },
    languages: [],
    challengeRating: "1/2",
    xp: 100,
    proficiencyBonus: 2,
    actions: [
      { name: "Crush", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Bludgeoning damage, and the darkmantle attaches to the target. If the target is a Medium or smaller creature and the darkmantle had Advantage on the attack roll, it covers the target, which has the Blinded condition and is suffocating while the darkmantle is attached in this way. While attached to a target, the darkmantle can attack only the target but has Advantage on its attack rolls. Its Speed becomes 0, it can’t benefit from any bonus to its Speed, and it moves with the target. A creature can take an action to try to detach the darkmantle from itself, doing so with a successful DC 13 Strength (Athletics) check. On its turn, the darkmantle can detach itself by using 5 feet of movement." },
      { name: "Darkness Aura (1/Day)", text: "Magical Darkness fills a 15-foot Emanation originating from the darkmantle. This effect lasts while the darkmantle maintains Concentration on it, up to 10 minutes. Darkvision can’t penetrate this area, and no light can illuminate it." },
    ],
  },
  {
    id: "gibbering-mouther",
    name: "Gibbering Mouther",
    type: "Aberration",
    size: "Medium",
    alignment: "Chaotic Neutral",
    armorClass: 9,
    hp: 52,
    hitDice: "7d8 + 21",
    initiative: { modifier: -1, score: 9 },
    speed: { walk: 20, swim: 20 },
    stats: { str: 10, dex: 8, con: 16, int: 3, wis: 10, cha: 6 },
    conditionImmunities: ["Prone"],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: [],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    traits: [
      { name: "Aberrant Ground", text: "The ground in a 10-foot Emanation originating from the mouther is Difficult Terrain." },
      { name: "Gibbering", text: "The mouther babbles incoherently while it doesn’t have the Incapacitated condition. Wisdom Saving Throw: DC 10, any creature that starts its turn within 20 feet of the mouther while it is babbling. Failure: The target rolls 1d8 to determine what it does during the current turn: 1–4. The target does nothing. 5–6. The target takes no action or Bonus Action and uses all its movement to move in a random direction. 7–8. The target makes a melee attack against a randomly determined creature within its reach or does nothing if it can’t make such an attack." },
    ],
    actions: [
      { name: "Bite", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 7 (2d6) Piercing damage. If the target is a Medium or smaller creature, it has the Prone condition. The target dies if it is reduced to 0 Hit Points by this attack. Its body is then absorbed into the mouther, leaving only equipment behind." },
      { name: "Blinding Spittle (Recharge 5–6)", text: "Dexterity Saving Throw: DC 10, each creature in a 10-foot-radius Sphere centered on a point within 30 feet. Failure: 7 (2d6) Radiant damage, and the target has the Blinded condition until the end of the mouther’s next turn." },
    ],
  },
  {
    id: "grick",
    name: "Grick",
    type: "Aberration",
    size: "Medium",
    alignment: "Unaligned",
    armorClass: 14,
    hp: 54,
    hitDice: "12d8",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, climb: 30 },
    stats: { str: 14, dex: 14, con: 11, int: 3, wis: 14, cha: 5 },
    skills: { Stealth: 4 },
    senses: { darkvision: 60, passivePerception: 12 },
    languages: [],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The grick makes one Beak attack and one Tentacles attack." },
      { name: "Beak", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 9 (2d6 + 2) Piercing damage." },
      { name: "Tentacles", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 7 (1d10 + 2) Slashing damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 12) from all four tentacles." },
    ],
  },
  {
    id: "grimlock",
    name: "Grimlock",
    type: "Aberration",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 11,
    hp: 11,
    hitDice: "2d8 + 2",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 30, climb: 30 },
    stats: { str: 16, dex: 12, con: 12, int: 9, wis: 8, cha: 6 },
    skills: { Athletics: 5, Perception: 3, Stealth: 5 },
    senses: { blindsight: 30, passivePerception: 13 },
    languages: [],
    challengeRating: "1/4",
    xp: 50,
    proficiencyBonus: 2,
    actions: [
      { name: "Bone Cudgel", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Bludgeoning damage plus 2 (1d4) Psychic damage." },
    ],
  },
  {
    id: "otyugh",
    name: "Otyugh",
    type: "Aberration",
    size: "Large",
    alignment: "Neutral",
    armorClass: 14,
    hp: 104,
    hitDice: "11d10 + 44",
    initiative: { modifier: 0, score: 10 },
    speed: { walk: 30 },
    stats: { str: 16, dex: 11, con: 19, int: 6, wis: 13, cha: 6 },
    savingThrows: { con: 7 },
    senses: { darkvision: 120, passivePerception: 11 },
    languages: ["Otyugh", "Telepathy 120 ft. (doesn’t allow the receiving creature to respond telepathically)"],
    challengeRating: "5",
    xp: 1800,
    proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The otyugh makes one Bite attack and two Tentacle attacks." },
      { name: "Bite", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 12 (2d8 + 3) Piercing damage, and the target has the Poisoned condition. Whenever the Poisoned target finishes a Long Rest, it is subjected to the following effect. Constitution Saving Throw: DC 15. Failure: The target’s Hit Point maximum decreases by 5 (1d10) and doesn’t return to normal until the Poisoned condition ends on the target. Success: The Poisoned condition ends." },
      { name: "Tentacle", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 12 (2d8 + 3) Piercing damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 13) from one of two tentacles." },
      { name: "Tentacle Slam", text: "Constitution Saving Throw: DC 14, each creature Grappled by the otyugh. Failure: 16 (3d8 + 3) Bludgeoning damage, and the target has the Stunned condition until the start of the otyugh’s next turn. Success: Half damage only." },
    ],
  },
  {
    id: "roper",
    name: "Roper",
    type: "Aberration",
    size: "Large",
    alignment: "Neutral Evil",
    armorClass: 20,
    hp: 93,
    hitDice: "11d10 + 33",
    initiative: { modifier: 5, score: 15 },
    speed: { walk: 10, climb: 20 },
    stats: { str: 18, dex: 8, con: 17, int: 7, wis: 16, cha: 6 },
    skills: { Perception: 6, Stealth: 5 },
    senses: { darkvision: 60, passivePerception: 16 },
    languages: [],
    challengeRating: "5",
    xp: 1800,
    proficiencyBonus: 3,
    traits: [
      { name: "Spider Climb", text: "The roper can climb difficult surfaces, including along ceilings, without needing to make an ability check." },
    ],
    actions: [
      { name: "Multiattack", text: "The roper makes two Tentacle attacks, uses Reel, and makes two Bite attacks." },
      { name: "Bite", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 17 (3d8 + 4) Piercing damage." },
      { name: "Tentacle", text: "Melee Attack Roll: +7, reach 60 ft. Hit: The target has the Grappled condition (escape DC 14) from one of six tentacles, and the target has the Poisoned condition until the grapple ends. The tentacle can be damaged, freeing a creature it has Grappled when destroyed (AC 20, HP 10, Immunity to Poison and Psychic damage). Damaging the tentacle deals no damage to the roper, and a destroyed tentacle regrows at the start of the roper’s next turn." },
      { name: "Reel", text: "The roper pulls each creature Grappled by it up to 30 feet straight toward it." },
    ],
  },
];
