import type { MonsterDefinition } from "../monsterTypes";

export const beasts: MonsterDefinition[] = [
  {
    id: "allosaurus", name: "Allosaurus", type: "Beast", subtype: "Dinosaur",
    size: "Large", alignment: "Unaligned", armorClass: 13, hp: 51, hitDice: "6d10 + 18",
    initiative: { modifier: 1, score: 11 }, speed: { walk: 60 },
    stats: { str: 19, dex: 13, con: 17, int: 2, wis: 12, cha: 5 },
    skills: { Perception: 5 }, senses: { passivePerception: 15 }, languages: [],
    challengeRating: "2", xp: 450, proficiencyBonus: 2,
    actions: [
      { name: "Bite", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 15 (2d10 + 4) Piercing damage." },
      { name: "Claws", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 8 (1d8 + 4) Slashing damage. After moving at least 30 feet straight toward a Large or smaller target before the hit, the target falls Prone and the allosaurus can make one Bite attack against it." },
    ],
  },
  {
    id: "ankylosaurus", name: "Ankylosaurus", type: "Beast", subtype: "Dinosaur",
    size: "Huge", alignment: "Unaligned", armorClass: 15, hp: 68, hitDice: "8d12 + 16",
    initiative: { modifier: 0, score: 10 }, speed: { walk: 30 },
    stats: { str: 19, dex: 11, con: 15, int: 2, wis: 12, cha: 5 },
    savingThrows: { str: 6 }, senses: { passivePerception: 11 }, languages: [],
    challengeRating: "3", xp: 700, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The ankylosaurus makes two Tail attacks." },
      { name: "Tail", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 9 (1d10 + 4) Bludgeoning damage. A Huge or smaller target also falls Prone." },
    ],
  },
  {
    id: "ape", name: "Ape", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 12, hp: 19, hitDice: "3d8 + 6", initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, climb: 30 }, stats: { str: 16, dex: 14, con: 14, int: 6, wis: 12, cha: 7 },
    skills: { Athletics: 5, Perception: 3 }, senses: { passivePerception: 13 }, languages: [],
    challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The ape makes two Fist attacks." },
      { name: "Fist", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Bludgeoning damage." },
      { name: "Rock (Recharge 6)", text: "Ranged Attack Roll: +5, range 25/50 ft. Hit: 10 (2d6 + 3) Bludgeoning damage." },
    ],
  },
  {
    id: "archelon", name: "Archelon", type: "Beast", subtype: "Dinosaur",
    size: "Huge", alignment: "Unaligned", armorClass: 17, hp: 90, hitDice: "12d12 + 12",
    initiative: { modifier: 3, score: 13 }, speed: { walk: 20, swim: 80 },
    stats: { str: 18, dex: 16, con: 13, int: 4, wis: 14, cha: 6 },
    skills: { Stealth: 5 }, senses: { passivePerception: 12 }, languages: [],
    challengeRating: "4", xp: 1100, proficiencyBonus: 2,
    traits: [{ name: "Amphibious", text: "The archelon can breathe air and water." }],
    actions: [
      { name: "Multiattack", text: "The archelon makes two Bite attacks." },
      { name: "Bite", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 14 (3d6 + 4) Piercing damage." },
    ],
  },
  {
    id: "baboon", name: "Baboon", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 12, hp: 3, hitDice: "1d6", initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, climb: 30 }, stats: { str: 8, dex: 14, con: 11, int: 4, wis: 12, cha: 6 },
    senses: { passivePerception: 11 }, languages: [], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The baboon has Advantage on an attack roll against a creature while an ally of the baboon is within 5 feet of that creature and isn't Incapacitated." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +1, reach 5 ft. Hit: 1 (1d4 − 1) Piercing damage." }],
  },
  {
    id: "badger", name: "Badger", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 11, hp: 5, hitDice: "1d4 + 3", initiative: { modifier: 0, score: 10 },
    speed: { walk: 20, burrow: 5 }, stats: { str: 10, dex: 11, con: 16, int: 2, wis: 12, cha: 5 },
    skills: { Perception: 3 }, damageResistances: ["Poison"],
    senses: { darkvision: 30, passivePerception: 13 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "bat", name: "Bat", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 12, hp: 1, hitDice: "1d4 − 1", initiative: { modifier: 2, score: 12 },
    speed: { walk: 5, fly: 30 }, stats: { str: 2, dex: 15, con: 8, int: 2, wis: 12, cha: 4 },
    senses: { blindsight: 60, passivePerception: 11 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "black-bear", name: "Black Bear", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 11, hp: 19, hitDice: "3d8 + 6", initiative: { modifier: 1, score: 11 },
    speed: { walk: 30, climb: 30, swim: 30 }, stats: { str: 15, dex: 12, con: 14, int: 2, wis: 12, cha: 7 },
    skills: { Perception: 5 }, senses: { darkvision: 60, passivePerception: 15 }, languages: [],
    challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The bear makes two Rend attacks." },
      { name: "Rend", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Slashing damage." },
    ],
  },
  {
    id: "blood-hawk", name: "Blood Hawk", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 12, hp: 7, hitDice: "2d6", initiative: { modifier: 2, score: 12 },
    speed: { walk: 10, fly: 60 }, stats: { str: 6, dex: 14, con: 10, int: 3, wis: 14, cha: 5 },
    skills: { Perception: 6 }, senses: { passivePerception: 16 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The hawk has Advantage on an attack roll against a creature while an ally of the hawk is within 5 feet of that creature and isn't Incapacitated." }],
    actions: [{ name: "Beak", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 4 (1d4 + 2) Piercing damage, or 6 (1d8 + 2) if the target is Bloodied." }],
  },
  {
    id: "boar", name: "Boar", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 11, hp: 13, hitDice: "2d8 + 4", initiative: { modifier: 0, score: 10 },
    speed: { walk: 40 }, stats: { str: 13, dex: 11, con: 14, int: 2, wis: 9, cha: 5 },
    senses: { passivePerception: 9 }, languages: [], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Bloodied Fury", text: "While Bloodied, the boar has Advantage on attack rolls." }],
    actions: [{ name: "Gore", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 4 (1d6 + 1) Piercing damage. After a 20-foot straight charge, a Medium or smaller target takes an extra 3 (1d6) Piercing damage and falls Prone." }],
  },
  {
    id: "brown-bear", name: "Brown Bear", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 11, hp: 22, hitDice: "3d10 + 6", initiative: { modifier: 1, score: 11 },
    speed: { walk: 40, climb: 30 }, stats: { str: 17, dex: 12, con: 15, int: 2, wis: 13, cha: 7 },
    skills: { Perception: 3 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The bear makes one Bite attack and one Claw attack." },
      { name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Piercing damage." },
      { name: "Claw", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Slashing damage. A Large or smaller target also falls Prone." },
    ],
  },
  {
    id: "camel", name: "Camel", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 10, hp: 17, hitDice: "2d10 + 6", initiative: { modifier: -1, score: 9 },
    speed: { walk: 50 }, stats: { str: 15, dex: 8, con: 17, int: 2, wis: 11, cha: 5 },
    savingThrows: { con: 5 }, senses: { darkvision: 60, passivePerception: 10 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 4 (1d4 + 2) Bludgeoning damage." }],
  },
  {
    id: "cat", name: "Cat", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 12, hp: 2, hitDice: "1d4", initiative: { modifier: 2, score: 12 },
    speed: { walk: 40, climb: 40 }, stats: { str: 3, dex: 15, con: 10, int: 3, wis: 12, cha: 7 },
    savingThrows: { dex: 4 }, skills: { Perception: 3, Stealth: 4 },
    senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Jumper", text: "The cat uses Dexterity rather than Strength when determining its jump distance." }],
    actions: [{ name: "Scratch", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 1 Slashing damage." }],
  },
  {
    id: "constrictor-snake", name: "Constrictor Snake", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 13, hitDice: "2d10 + 2", initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, swim: 30 }, stats: { str: 15, dex: 14, con: 12, int: 1, wis: 10, cha: 3 },
    skills: { Perception: 2, Stealth: 4 }, senses: { blindsight: 10, passivePerception: 12 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [
      { name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 6 (1d8 + 2) Piercing damage." },
      { name: "Constrict", text: "Strength Saving Throw: DC 12, one Medium or smaller creature within 5 ft. Failure: 7 (3d4) Bludgeoning damage and Grappled (escape DC 12)." },
    ],
  },
  {
    id: "crab", name: "Crab", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 11, hp: 3, hitDice: "1d4 + 1", initiative: { modifier: 0, score: 10 },
    speed: { walk: 20, swim: 20 }, stats: { str: 6, dex: 11, con: 12, int: 1, wis: 8, cha: 2 },
    skills: { Stealth: 2 }, senses: { blindsight: 30, passivePerception: 9 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Amphibious", text: "The crab can breathe air and water." }],
    actions: [{ name: "Claw", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 1 Bludgeoning damage." }],
  },
  {
    id: "crocodile", name: "Crocodile", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 12, hp: 13, hitDice: "2d10 + 2", initiative: { modifier: 0, score: 10 },
    speed: { walk: 20, swim: 30 }, stats: { str: 15, dex: 10, con: 13, int: 2, wis: 10, cha: 5 },
    savingThrows: { con: 3 }, skills: { Stealth: 2 }, senses: { passivePerception: 10 }, languages: [],
    challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    traits: [{ name: "Hold Breath", text: "The crocodile can hold its breath for 1 hour." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 6 (1d8 + 2) Piercing damage. A Medium or smaller target is Grappled (escape DC 12) and Restrained while grappled." }],
  },
  {
    id: "deer", name: "Deer", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 4, hitDice: "1d8", initiative: { modifier: 3, score: 13 },
    speed: { walk: 50 }, stats: { str: 11, dex: 16, con: 11, int: 2, wis: 14, cha: 5 },
    skills: { Perception: 4 }, senses: { darkvision: 60, passivePerception: 14 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Agile", text: "The deer doesn't provoke an Opportunity Attack when it moves out of an enemy's reach." }],
    actions: [{ name: "Ram", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 2 (1d4) Bludgeoning damage." }],
  },
  {
    id: "dire-wolf", name: "Dire Wolf", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 14, hp: 22, hitDice: "3d10 + 6", initiative: { modifier: 2, score: 12 },
    speed: { walk: 50 }, stats: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    skills: { Perception: 5, Stealth: 4 }, senses: { darkvision: 60, passivePerception: 15 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The wolf has Advantage on an attack roll against a creature while an ally of the wolf is within 5 feet of that creature and isn't Incapacitated." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 8 (1d10 + 3) Piercing damage. A Large or smaller target also falls Prone." }],
  },
  {
    id: "draft-horse", name: "Draft Horse", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 10, hp: 15, hitDice: "2d10 + 4", initiative: { modifier: 0, score: 10 },
    speed: { walk: 40 }, stats: { str: 18, dex: 10, con: 15, int: 2, wis: 11, cha: 7 },
    senses: { passivePerception: 10 }, languages: [], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Hooves", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 6 (1d4 + 4) Bludgeoning damage." }],
  },
  {
    id: "eagle", name: "Eagle", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 12, hp: 4, hitDice: "1d6 + 1", initiative: { modifier: 2, score: 12 },
    speed: { walk: 10, fly: 60 }, stats: { str: 6, dex: 15, con: 12, int: 2, wis: 14, cha: 7 },
    skills: { Perception: 6 }, senses: { passivePerception: 16 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    actions: [{ name: "Talons", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 4 (1d4 + 2) Slashing damage." }],
  },
  {
    id: "elephant", name: "Elephant", type: "Beast", size: "Huge", alignment: "Unaligned",
    armorClass: 12, hp: 76, hitDice: "8d12 + 24", initiative: { modifier: -1, score: 9 },
    speed: { walk: 40 }, stats: { str: 22, dex: 9, con: 17, int: 3, wis: 11, cha: 6 },
    senses: { passivePerception: 10 }, languages: [], challengeRating: "4", xp: 1100, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The elephant makes two Gore attacks." },
      { name: "Gore", text: "Melee Attack Roll: +8, reach 5 ft. Hit: 15 (2d8 + 6) Piercing damage. After a 20-foot straight charge, a Huge or smaller target also falls Prone." },
    ],
    bonusActions: [{ name: "Trample", text: "Dexterity Saving Throw: DC 16, one Prone creature within 5 ft. Failure: 17 (2d10 + 6) Bludgeoning damage. Success: Half damage." }],
  },
  {
    id: "elk", name: "Elk", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 10, hp: 11, hitDice: "2d10", initiative: { modifier: 0, score: 10 },
    speed: { walk: 50 }, stats: { str: 16, dex: 10, con: 11, int: 2, wis: 10, cha: 6 },
    skills: { Perception: 2 }, senses: { darkvision: 60, passivePerception: 12 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Ram", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Bludgeoning damage. After a 20-foot straight charge, a Large or smaller target takes an extra 3 (1d6) Bludgeoning damage and falls Prone." }],
  },
  {
    id: "frog", name: "Frog", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 11, hp: 1, hitDice: "1d4 − 1", initiative: { modifier: 1, score: 11 },
    speed: { walk: 20, swim: 20 }, stats: { str: 1, dex: 13, con: 8, int: 1, wis: 8, cha: 3 },
    skills: { Perception: 1, Stealth: 3 }, senses: { darkvision: 30, passivePerception: 11 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [
      { name: "Amphibious", text: "The frog can breathe air and water." },
      { name: "Standing Leap", text: "The frog can Long Jump 10 feet and High Jump 5 feet without needing a running start." },
    ],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "giant-ape", name: "Giant Ape", type: "Beast", size: "Huge", alignment: "Unaligned",
    armorClass: 12, hp: 168, hitDice: "16d12 + 64", initiative: { modifier: 5, score: 15 },
    speed: { walk: 40, climb: 40 }, stats: { str: 23, dex: 14, con: 18, int: 5, wis: 12, cha: 7 },
    skills: { Athletics: 9, Perception: 4, Survival: 4 }, senses: { passivePerception: 14 }, languages: [],
    challengeRating: "7", xp: 2900, proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The ape makes two Fist attacks." },
      { name: "Fist", text: "Melee Attack Roll: +9, reach 10 ft. Hit: 22 (3d10 + 6) Bludgeoning damage." },
      { name: "Boulder Toss (Recharge 6)", text: "Dexterity Saving Throw: DC 17, creatures in a 5-foot-radius Sphere centered on a point within 90 ft. Failure: 24 (7d6) Bludgeoning damage, and Large or smaller creatures fall Prone. Success: Half damage." },
    ],
    bonusActions: [{ name: "Leap", text: "By spending 10 feet of movement, the ape jumps up to 30 feet." }],
  },
  {
    id: "giant-badger", name: "Giant Badger", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 15, hitDice: "2d8 + 6", initiative: { modifier: 0, score: 10 },
    speed: { walk: 30, burrow: 10 }, stats: { str: 13, dex: 10, con: 17, int: 2, wis: 12, cha: 5 },
    skills: { Perception: 3 }, damageResistances: ["Poison"], senses: { darkvision: 60, passivePerception: 13 },
    languages: [], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 6 (2d4 + 1) Piercing damage." }],
  },
  {
    id: "giant-bat", name: "Giant Bat", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 22, hitDice: "4d10", initiative: { modifier: 3, score: 13 },
    speed: { walk: 10, fly: 60 }, stats: { str: 15, dex: 16, con: 11, int: 2, wis: 12, cha: 6 },
    senses: { blindsight: 120, passivePerception: 11 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage." }],
  },
  {
    id: "giant-boar", name: "Giant Boar", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 42, hitDice: "5d10 + 15", initiative: { modifier: 0, score: 10 },
    speed: { walk: 40 }, stats: { str: 17, dex: 10, con: 16, int: 2, wis: 7, cha: 5 },
    savingThrows: { str: 5 }, senses: { passivePerception: 8 }, languages: [],
    challengeRating: "2", xp: 450, proficiencyBonus: 2,
    traits: [{ name: "Bloodied Fury", text: "While Bloodied, the boar has Advantage on melee attack rolls." }],
    actions: [{ name: "Gore", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Piercing damage. After a 20-foot straight charge, a Large or smaller target takes an extra 7 (2d6) Piercing damage and falls Prone." }],
  },
  {
    id: "giant-centipede", name: "Giant Centipede", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 14, hp: 9, hitDice: "2d6 + 2", initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, climb: 30 }, stats: { str: 5, dex: 14, con: 12, int: 1, wis: 7, cha: 3 },
    senses: { blindsight: 30, passivePerception: 8 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 4 (1d4 + 2) Piercing damage, and the target is Poisoned until the start of the centipede's next turn." }],
  },
  {
    id: "giant-constrictor-snake", name: "Giant Constrictor Snake", type: "Beast", size: "Huge", alignment: "Unaligned",
    armorClass: 12, hp: 60, hitDice: "8d12 + 8", initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, swim: 30 }, stats: { str: 19, dex: 14, con: 12, int: 1, wis: 10, cha: 3 },
    skills: { Perception: 2 }, senses: { blindsight: 10, passivePerception: 12 }, languages: [],
    challengeRating: "2", xp: 450, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The snake makes one Bite attack and uses Constrict." },
      { name: "Bite", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 11 (2d6 + 4) Piercing damage." },
      { name: "Constrict", text: "Strength Saving Throw: DC 14, one Large or smaller creature within 10 ft. Failure: 13 (2d8 + 4) Bludgeoning damage and Grappled (escape DC 14)." },
    ],
  },
  {
    id: "giant-crab", name: "Giant Crab", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 15, hp: 13, hitDice: "3d8", initiative: { modifier: 1, score: 11 },
    speed: { walk: 30, swim: 30 }, stats: { str: 13, dex: 13, con: 11, int: 1, wis: 9, cha: 3 },
    skills: { Stealth: 3 }, senses: { blindsight: 30, passivePerception: 9 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    traits: [{ name: "Amphibious", text: "The crab can breathe air and water." }],
    actions: [{ name: "Claw", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 4 (1d6 + 1) Bludgeoning damage. A Medium or smaller target is Grappled (escape DC 11) by one of the crab's two claws." }],
  },
  {
    id: "giant-crocodile", name: "Giant Crocodile", type: "Beast", size: "Huge", alignment: "Unaligned",
    armorClass: 14, hp: 85, hitDice: "9d12 + 27", initiative: { modifier: -1, score: 9 },
    speed: { walk: 30, swim: 50 }, stats: { str: 21, dex: 9, con: 17, int: 2, wis: 10, cha: 7 },
    skills: { Stealth: 5 }, senses: { passivePerception: 10 }, languages: [],
    challengeRating: "5", xp: 1800, proficiencyBonus: 3,
    traits: [{ name: "Hold Breath", text: "The crocodile can hold its breath for 1 hour." }],
    actions: [
      { name: "Multiattack", text: "The crocodile makes one Bite attack and one Tail attack." },
      { name: "Bite", text: "Melee Attack Roll: +8, reach 5 ft. Hit: 21 (3d10 + 5) Piercing damage. A Large or smaller target is Grappled (escape DC 15) and Restrained while grappled; the target can't then be targeted by Tail." },
      { name: "Tail", text: "Melee Attack Roll: +8, reach 10 ft. Hit: 18 (3d8 + 5) Bludgeoning damage. A Large or smaller target also falls Prone." },
    ],
  },
  {
    id: "giant-fire-beetle", name: "Giant Fire Beetle", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 13, hp: 4, hitDice: "1d6 + 1", initiative: { modifier: 0, score: 10 },
    speed: { walk: 30, climb: 30 }, stats: { str: 8, dex: 10, con: 12, int: 1, wis: 7, cha: 3 },
    damageResistances: ["Fire"], senses: { blindsight: 30, passivePerception: 8 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Illumination", text: "The beetle sheds Bright Light for 10 feet and Dim Light for another 10 feet." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +1, reach 5 ft. Hit: 1 Fire damage." }],
  },
  {
    id: "giant-frog", name: "Giant Frog", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 11, hp: 18, hitDice: "4d8", initiative: { modifier: 1, score: 11 },
    speed: { walk: 30, swim: 30 }, stats: { str: 12, dex: 13, con: 11, int: 2, wis: 10, cha: 3 },
    skills: { Perception: 2, Stealth: 4 }, senses: { darkvision: 30, passivePerception: 12 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [
      { name: "Amphibious", text: "The frog can breathe air and water." },
      { name: "Standing Leap", text: "The frog can Long Jump 20 feet and High Jump 10 feet without a running start." },
    ],
    actions: [
      { name: "Bite", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage. A Medium or smaller target is Grappled (escape DC 11)." },
      { name: "Swallow", text: "The frog swallows a Small or smaller creature it is grappling. The swallowed creature is Blinded and Restrained and has Total Cover from outside effects. At the end of the frog's next turn it takes 5 (2d4) Acid damage; if it survives, the frog disgorges it Prone." },
    ],
  },
  {
    id: "giant-goat", name: "Giant Goat", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 11, hp: 19, hitDice: "3d10 + 3", initiative: { modifier: 1, score: 11 },
    speed: { walk: 40, climb: 30 }, stats: { str: 17, dex: 13, con: 12, int: 3, wis: 12, cha: 6 },
    savingThrows: { str: 5 }, skills: { Perception: 3 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    actions: [{ name: "Ram", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Bludgeoning damage. After a 20-foot straight charge, a Large or smaller target takes an extra 5 (2d4) Bludgeoning damage and falls Prone." }],
  },
  {
    id: "giant-hyena", name: "Giant Hyena", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 12, hp: 45, hitDice: "6d10 + 12", initiative: { modifier: 2, score: 12 },
    speed: { walk: 50 }, stats: { str: 16, dex: 14, con: 14, int: 2, wis: 12, cha: 7 },
    skills: { Perception: 3 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Piercing damage." }],
    bonusActions: [{ name: "Rampage (1/Day)", text: "Immediately after damaging a creature that was already Bloodied, the hyena can move up to half its Speed and make one Bite attack." }],
  },
  {
    id: "giant-lizard", name: "Giant Lizard", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 12, hp: 19, hitDice: "3d10 + 3", initiative: { modifier: 1, score: 11 },
    speed: { walk: 40, climb: 40 }, stats: { str: 15, dex: 12, con: 13, int: 2, wis: 10, cha: 5 },
    savingThrows: { dex: 3 }, senses: { darkvision: 60, passivePerception: 10 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Spider Climb", text: "The lizard can climb difficult surfaces and ceilings without an ability check." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 6 (1d8 + 2) Piercing damage." }],
  },
  {
    id: "giant-octopus", name: "Giant Octopus", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 11, hp: 45, hitDice: "7d10 + 7", initiative: { modifier: 1, score: 11 },
    speed: { walk: 10, swim: 60 }, stats: { str: 17, dex: 13, con: 13, int: 5, wis: 10, cha: 4 },
    skills: { Perception: 4, Stealth: 5 }, senses: { darkvision: 60, passivePerception: 14 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    traits: [{ name: "Water Breathing", text: "The octopus breathes only underwater but can hold its breath for 1 hour outside water." }],
    actions: [{ name: "Tentacles", text: "Melee Attack Roll: +5, reach 10 ft. Hit: 10 (2d6 + 3) Bludgeoning damage. A Medium or smaller target is Grappled (escape DC 13) and Restrained while grappled." }],
    reactions: [{ name: "Ink Cloud (1/Day)", text: "When damaged underwater, the octopus creates a Heavily Obscured 10-foot Cube centered on itself and moves up to its Swim Speed. The ink lasts 1 minute unless dispersed." }],
  },
  {
    id: "giant-rat", name: "Giant Rat", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 13, hp: 7, hitDice: "2d6", initiative: { modifier: 3, score: 13 },
    speed: { walk: 30, climb: 30 }, stats: { str: 7, dex: 16, con: 11, int: 2, wis: 10, cha: 4 },
    savingThrows: { dex: 5 }, skills: { Perception: 2 }, senses: { darkvision: 60, passivePerception: 12 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The rat has Advantage on an attack roll against a creature while an ally of the rat is within 5 feet of that creature and isn't Incapacitated." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Piercing damage." }],
  },
  {
    id: "giant-scorpion", name: "Giant Scorpion", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 15, hp: 52, hitDice: "7d10 + 14", initiative: { modifier: 1, score: 11 },
    speed: { walk: 40 }, stats: { str: 16, dex: 13, con: 15, int: 1, wis: 9, cha: 3 },
    senses: { blindsight: 60, passivePerception: 9 }, languages: [],
    challengeRating: "3", xp: 700, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The scorpion makes two Claw attacks and one Sting attack." },
      { name: "Claw", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Bludgeoning damage. A Large or smaller target is Grappled (escape DC 13) by one of two claws." },
      { name: "Sting", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Piercing damage plus 11 (2d10) Poison damage." },
    ],
  },
  {
    id: "giant-seahorse", name: "Giant Seahorse", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 14, hp: 16, hitDice: "3d10", initiative: { modifier: 1, score: 11 },
    speed: { walk: 5, swim: 40 }, stats: { str: 15, dex: 12, con: 11, int: 2, wis: 12, cha: 5 },
    senses: { passivePerception: 11 }, languages: [], challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    traits: [{ name: "Water Breathing", text: "The seahorse can breathe only underwater." }],
    actions: [{ name: "Ram", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 9 (2d6 + 2) Bludgeoning damage, or 11 (2d8 + 2) after moving at least 20 feet straight toward the target." }],
    bonusActions: [{ name: "Bubble Dash", text: "While underwater, the seahorse moves up to half its Swim Speed without provoking Opportunity Attacks." }],
  },
  {
    id: "giant-shark", name: "Giant Shark", type: "Beast", size: "Huge", alignment: "Unaligned",
    armorClass: 13, hp: 92, hitDice: "8d12 + 40", initiative: { modifier: 3, score: 13 },
    speed: { walk: 5, swim: 60 }, stats: { str: 23, dex: 11, con: 21, int: 1, wis: 10, cha: 5 },
    skills: { Perception: 3 }, senses: { blindsight: 60, passivePerception: 13 }, languages: [],
    challengeRating: "5", xp: 1800, proficiencyBonus: 3,
    traits: [{ name: "Water Breathing", text: "The shark can breathe only underwater." }],
    actions: [
      { name: "Multiattack", text: "The shark makes two Bite attacks." },
      { name: "Bite", text: "Melee Attack Roll: +9, with Advantage against a target missing any Hit Points, reach 5 ft. Hit: 22 (3d10 + 6) Piercing damage." },
    ],
  },
  {
    id: "giant-spider", name: "Giant Spider", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 14, hp: 26, hitDice: "4d10 + 4", initiative: { modifier: 3, score: 13 },
    speed: { walk: 30, climb: 30 }, stats: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    skills: { Perception: 4, Stealth: 7 }, senses: { darkvision: 60, passivePerception: 14 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    traits: [
      { name: "Spider Climb", text: "The spider can climb difficult surfaces and ceilings without an ability check." },
      { name: "Web Walker", text: "The spider ignores movement restrictions from webs and knows the location of creatures touching the same web." },
    ],
    actions: [
      { name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Piercing damage plus 7 (2d6) Poison damage." },
      { name: "Web (Recharge 5–6)", text: "Dexterity Saving Throw: DC 13, one creature within 60 ft. Failure: Restrained until the web is destroyed (AC 10, HP 5, Vulnerable to Fire, Immune to Poison and Psychic damage)." },
    ],
  },
  {
    id: "giant-toad", name: "Giant Toad", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 11, hp: 39, hitDice: "6d10 + 6", initiative: { modifier: 1, score: 11 },
    speed: { walk: 30, swim: 30 }, stats: { str: 15, dex: 13, con: 13, int: 2, wis: 10, cha: 3 },
    senses: { darkvision: 60, passivePerception: 10 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    traits: [
      { name: "Amphibious", text: "The toad can breathe air and water." },
      { name: "Standing Leap", text: "The toad can Long Jump 20 feet and High Jump 10 feet without a running start." },
    ],
    actions: [
      { name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing plus 5 (2d4) Poison damage. A Medium or smaller target is Grappled (escape DC 12)." },
      { name: "Swallow", text: "The toad swallows a Medium or smaller creature it is grappling. The creature becomes Blinded and Restrained, has Total Cover from outside effects, and takes 10 (3d6) Acid damage at the end of each of the toad's turns. The toad can hold one swallowed creature." },
    ],
  },
  {
    id: "giant-venomous-snake", name: "Giant Venomous Snake", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 14, hp: 11, hitDice: "2d8 + 2", initiative: { modifier: 4, score: 14 },
    speed: { walk: 40, swim: 40 }, stats: { str: 10, dex: 18, con: 13, int: 2, wis: 10, cha: 3 },
    skills: { Perception: 2 }, senses: { blindsight: 10, passivePerception: 12 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 6 (1d4 + 4) Piercing damage plus 4 (1d8) Poison damage." }],
  },
  {
    id: "giant-wasp", name: "Giant Wasp", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 22, hitDice: "5d8", initiative: { modifier: 2, score: 12 },
    speed: { walk: 10, fly: 50 }, stats: { str: 10, dex: 14, con: 10, int: 1, wis: 10, cha: 3 },
    senses: { passivePerception: 10 }, languages: [], challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    traits: [{ name: "Flyby", text: "The wasp doesn't provoke an Opportunity Attack when it flies out of an enemy's reach." }],
    actions: [{ name: "Sting", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage plus 5 (2d4) Poison damage." }],
  },
  {
    id: "giant-weasel", name: "Giant Weasel", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 9, hitDice: "2d8", initiative: { modifier: 3, score: 13 },
    speed: { walk: 40, climb: 30 }, stats: { str: 11, dex: 17, con: 10, int: 4, wis: 12, cha: 5 },
    skills: { Acrobatics: 5, Perception: 3, Stealth: 5 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Piercing damage." }],
  },
  {
    id: "giant-wolf-spider", name: "Giant Wolf Spider", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 11, hitDice: "2d8 + 2", initiative: { modifier: 3, score: 13 },
    speed: { walk: 40, climb: 40 }, stats: { str: 12, dex: 16, con: 13, int: 3, wis: 12, cha: 4 },
    skills: { Perception: 3, Stealth: 7 }, senses: { blindsight: 10, darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Spider Climb", text: "The spider can climb difficult surfaces and ceilings without an ability check." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Piercing damage plus 5 (2d4) Poison damage." }],
  },
  {
  id: "goat",
  name: "Goat",
  type: "Beast",
  size: "Medium",
  alignment: "Unaligned",

  armorClass: 10,
  hp: 4,
  hitDice: "1d8",

  initiative: {
    modifier: 0,
    score: 10,
  },

  speed: {
    walk: 40,
    climb: 30,
  },

  stats: {
    str: 11,
    dex: 10,
    con: 11,
    int: 2,
    wis: 10,
    cha: 5,
  },

  savingThrows: {
    str: 2,
  },

  skills: {
    Perception: 2,
  },

  senses: {
    darkvision: 60,
    passivePerception: 12,
  },

  languages: [],

  challengeRating: "0",
  xp: 10,
  proficiencyBonus: 2,

  actions: [
    {
      name: "Ram",
      text: "Melee Attack Roll: +2, reach 5 ft. Hit: 1 Bludgeoning damage, or 2 (1d4) Bludgeoning damage if the goat moved 20+ feet straight toward the target immediately before the hit.",
    },
  ],
},
  {
    id: "hawk", name: "Hawk", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 13, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 3, score: 13 },
    speed: { walk: 10, fly: 60 }, stats: { str: 5, dex: 16, con: 8, int: 2, wis: 14, cha: 6 },
    skills: { Perception: 6 }, senses: { passivePerception: 16 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    actions: [{ name: "Talons", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 1 Slashing damage." }],
  },
  {
    id: "hippopotamus", name: "Hippopotamus", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 14, hp: 82, hitDice: "11d10 + 22", initiative: { modifier: -2, score: 8 },
    speed: { walk: 30, swim: 30 }, stats: { str: 21, dex: 7, con: 15, int: 2, wis: 12, cha: 4 },
    savingThrows: { str: 7 }, skills: { Perception: 3 }, senses: { passivePerception: 13 }, languages: [],
    challengeRating: "4", xp: 1100, proficiencyBonus: 2,
    traits: [{ name: "Hold Breath", text: "The hippopotamus can hold its breath for 10 minutes." }],
    actions: [
      { name: "Multiattack", text: "The hippopotamus makes two Bite attacks." },
      { name: "Bite", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 16 (2d10 + 5) Piercing damage." },
    ],
  },
  {
    id: "hunter-shark", name: "Hunter Shark", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 12, hp: 45, hitDice: "6d10 + 12", initiative: { modifier: 2, score: 12 },
    speed: { walk: 5, swim: 40 }, stats: { str: 18, dex: 14, con: 15, int: 1, wis: 10, cha: 4 },
    skills: { Perception: 2 }, senses: { blindsight: 60, passivePerception: 12 }, languages: [],
    challengeRating: "2", xp: 450, proficiencyBonus: 2,
    traits: [{ name: "Water Breathing", text: "The shark can breathe only underwater." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +6, with Advantage if the target doesn't have all its Hit Points, reach 5 ft. Hit: 14 (3d6 + 4) Piercing damage." }],
  },
  {
    id: "hyena", name: "Hyena", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 11, hp: 5, hitDice: "1d8 + 1", initiative: { modifier: 1, score: 11 },
    speed: { walk: 50 }, stats: { str: 11, dex: 13, con: 12, int: 2, wis: 12, cha: 5 },
    skills: { Perception: 3 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The hyena has Advantage on an attack roll against a creature if at least one ally is within 5 feet of the creature and isn't Incapacitated." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 3 (1d6) Piercing damage." }],
  },
  {
    id: "jackal", name: "Jackal", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 12, hp: 3, hitDice: "1d6", initiative: { modifier: 2, score: 12 },
    speed: { walk: 40 }, stats: { str: 8, dex: 15, con: 11, int: 3, wis: 12, cha: 6 },
    skills: { Perception: 3 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The jackal has Advantage on an attack roll against a creature if at least one ally is within 5 feet of the creature and isn't Incapacitated." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "killer-whale", name: "Killer Whale", type: "Beast", size: "Huge", alignment: "Unaligned",
    armorClass: 12, hp: 90, hitDice: "12d12 + 12", initiative: { modifier: 0, score: 10 },
    speed: { walk: 5, swim: 60 }, stats: { str: 19, dex: 10, con: 13, int: 3, wis: 12, cha: 7 },
    skills: { Perception: 5 }, senses: { blindsight: 120, passivePerception: 15 }, languages: [],
    challengeRating: "3", xp: 700, proficiencyBonus: 2,
    traits: [{ name: "Hold Breath", text: "The whale can hold its breath for 30 minutes." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 21 (5d6 + 4) Piercing damage." }],
  },
  {
    id: "lion", name: "Lion", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 12, hp: 22, hitDice: "4d10", initiative: { modifier: 2, score: 12 },
    speed: { walk: 50 }, stats: { str: 17, dex: 15, con: 11, int: 3, wis: 12, cha: 8 },
    skills: { Perception: 3, Stealth: 6 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    actions: [{ name: "Rend", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Slashing damage." }],
    bonusActions: [{ name: "Roar (Recharge 6)", text: "Wisdom Saving Throw: DC 11, each enemy in a 15-foot Emanation. Failure: Frightened until the start of the lion's next turn." }],
  },
  {
    id: "lizard", name: "Lizard", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 10, hp: 2, hitDice: "1d4", initiative: { modifier: 0, score: 10 },
    speed: { walk: 20, climb: 20 }, stats: { str: 2, dex: 11, con: 10, int: 1, wis: 8, cha: 3 },
    senses: { darkvision: 30, passivePerception: 9 }, languages: [], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Spider Climb", text: "The lizard can climb difficult surfaces, including along ceilings, without needing to make an ability check." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "mammoth", name: "Mammoth", type: "Beast", size: "Huge", alignment: "Unaligned",
    armorClass: 13, hp: 126, hitDice: "11d12 + 55", initiative: { modifier: 2, score: 12 },
    speed: { walk: 50 }, stats: { str: 24, dex: 9, con: 21, int: 3, wis: 11, cha: 6 },
    savingThrows: { str: 10, con: 8 }, senses: { passivePerception: 10 }, languages: [],
    challengeRating: "6", xp: 2300, proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The mammoth makes two Gore attacks." },
      { name: "Gore", text: "Melee Attack Roll: +10, reach 10 ft. Hit: 18 (2d10 + 7) Piercing damage. After moving 20+ feet straight toward a Huge or smaller target, the target also falls Prone." },
    ],
    bonusActions: [{ name: "Trample", text: "Dexterity Saving Throw: DC 18, one Prone creature within 5 ft. Failure: 29 (4d10 + 7) Bludgeoning damage. Success: Half damage." }],
  },
  {
    id: "mastiff", name: "Mastiff", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 12, hp: 5, hitDice: "1d8 + 1", initiative: { modifier: 2, score: 12 },
    speed: { walk: 40 }, stats: { str: 13, dex: 14, con: 12, int: 3, wis: 12, cha: 7 },
    savingThrows: { wis: 3 }, skills: { Perception: 5 }, senses: { darkvision: 60, passivePerception: 15 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 4 (1d6 + 1) Piercing damage. A Medium or smaller target also falls Prone." }],
  },
  {
    id: "mule", name: "Mule", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 10, hp: 11, hitDice: "2d8 + 2", initiative: { modifier: 0, score: 10 },
    speed: { walk: 40 }, stats: { str: 14, dex: 10, con: 13, int: 2, wis: 10, cha: 5 },
    savingThrows: { str: 4 }, senses: { passivePerception: 10 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    traits: [{ name: "Beast of Burden", text: "The mule counts as one size larger when determining its carrying capacity." }],
    actions: [{ name: "Hooves", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 4 (1d4 + 2) Bludgeoning damage." }],
  },
  {
    id: "octopus", name: "Octopus", type: "Beast", size: "Small", alignment: "Unaligned",
    armorClass: 12, hp: 3, hitDice: "1d6", initiative: { modifier: 2, score: 12 },
    speed: { walk: 5, swim: 30 }, stats: { str: 4, dex: 15, con: 11, int: 3, wis: 10, cha: 4 },
    skills: { Perception: 2, Stealth: 6 }, senses: { darkvision: 30, passivePerception: 12 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [
      { name: "Compression", text: "The octopus can move through a space as narrow as 1 inch without extra movement." },
      { name: "Water Breathing", text: "The octopus can breathe only underwater." },
    ],
    actions: [{ name: "Tentacles", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 1 Bludgeoning damage." }],
    reactions: [{ name: "Ink Cloud (1/Day)", text: "When a creature ends its turn within 5 feet while underwater, the octopus creates a Heavily Obscured 5-foot Cube centered on itself and moves up to its Swim Speed. The ink lasts 1 minute or until dispersed." }],
  },
  {
    id: "owl", name: "Owl", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 11, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 1, score: 11 },
    speed: { walk: 5, fly: 60 }, stats: { str: 3, dex: 13, con: 8, int: 2, wis: 12, cha: 7 },
    skills: { Perception: 5, Stealth: 5 }, senses: { darkvision: 120, passivePerception: 15 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Flyby", text: "The owl doesn't provoke an Opportunity Attack when it flies out of an enemy's reach." }],
    actions: [{ name: "Talons", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 1 Slashing damage." }],
  },
  {
    id: "panther", name: "Panther", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 13, hitDice: "3d8", initiative: { modifier: 3, score: 13 },
    speed: { walk: 50, climb: 40 }, stats: { str: 14, dex: 16, con: 10, int: 3, wis: 14, cha: 7 },
    skills: { Perception: 4, Stealth: 7 }, senses: { darkvision: 60, passivePerception: 14 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Rend", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Slashing damage." }],
    bonusActions: [{ name: "Nimble Escape", text: "The panther takes the Disengage or Hide action." }],
  },
  {
    id: "piranha", name: "Piranha", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 13, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 3, score: 13 },
    speed: { walk: 5, swim: 40 }, stats: { str: 2, dex: 16, con: 9, int: 1, wis: 7, cha: 2 },
    senses: { darkvision: 60, passivePerception: 8 }, languages: [], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Water Breathing", text: "The piranha can breathe only underwater." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, with Advantage if the target doesn't have all its Hit Points, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "plesiosaurus", name: "Plesiosaurus", type: "Beast", subtype: "Dinosaur", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 68, hitDice: "8d10 + 24", initiative: { modifier: 2, score: 12 },
    speed: { walk: 20, swim: 40 }, stats: { str: 18, dex: 15, con: 16, int: 2, wis: 12, cha: 5 },
    skills: { Perception: 3, Stealth: 4 }, senses: { passivePerception: 13 }, languages: [],
    challengeRating: "2", xp: 450, proficiencyBonus: 2,
    traits: [{ name: "Hold Breath", text: "The plesiosaurus can hold its breath for 1 hour." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 14 (3d6 + 4) Piercing damage." }],
  },
  {
    id: "polar-bear", name: "Polar Bear", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 42, hitDice: "5d10 + 15", initiative: { modifier: 0, score: 10 },
    speed: { walk: 40, swim: 30 }, stats: { str: 20, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    skills: { Perception: 5 }, senses: { darkvision: 60, passivePerception: 15 }, languages: [],
    challengeRating: "2", xp: 450, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The bear makes one Bite attack and one Claw attack." },
      { name: "Bite", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 9 (1d8 + 5) Piercing damage." },
      { name: "Claw", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 8 (1d6 + 5) Slashing damage. A Large or smaller target also falls Prone." },
    ],
  },
  {
    id: "pony", name: "Pony", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 10, hp: 11, hitDice: "2d8 + 2", initiative: { modifier: 0, score: 10 },
    speed: { walk: 40 }, stats: { str: 15, dex: 10, con: 13, int: 2, wis: 11, cha: 7 },
    savingThrows: { str: 4 }, senses: { passivePerception: 10 }, languages: [],
    challengeRating: "1/8", xp: 25, proficiencyBonus: 2,
    actions: [{ name: "Hooves", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 4 (1d4 + 2) Bludgeoning damage." }],
  },
  {
    id: "pteranodon", name: "Pteranodon", type: "Beast", subtype: "Dinosaur", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 13, hitDice: "3d8", initiative: { modifier: 2, score: 12 },
    speed: { walk: 10, fly: 60 }, stats: { str: 12, dex: 15, con: 10, int: 2, wis: 9, cha: 5 },
    skills: { Perception: 1 }, senses: { passivePerception: 11 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Flyby", text: "The pteranodon doesn't provoke an Opportunity Attack when it flies out of an enemy's reach." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 6 (1d8 + 2) Piercing damage." }],
  },
  {
    id: "rat", name: "Rat", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 10, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 0, score: 10 },
    speed: { walk: 20, climb: 20 }, stats: { str: 2, dex: 11, con: 9, int: 2, wis: 10, cha: 4 },
    skills: { Perception: 2 }, senses: { darkvision: 30, passivePerception: 12 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Agile", text: "The rat doesn't provoke an Opportunity Attack when it moves out of an enemy's reach." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "raven", name: "Raven", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 12, hp: 2, hitDice: "1d4", initiative: { modifier: 2, score: 12 },
    speed: { walk: 10, fly: 50 }, stats: { str: 2, dex: 14, con: 10, int: 5, wis: 13, cha: 6 },
    skills: { Perception: 3 }, senses: { passivePerception: 13 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Mimicry", text: "The raven can mimic simple sounds it has heard. A hearer can identify the imitation with a successful DC 10 Wisdom (Insight) check." }],
    actions: [{ name: "Beak", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "reef-shark", name: "Reef Shark", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 12, hp: 22, hitDice: "4d8 + 4", initiative: { modifier: 2, score: 12 },
    speed: { walk: 5, swim: 30 }, stats: { str: 14, dex: 15, con: 13, int: 1, wis: 10, cha: 4 },
    skills: { Perception: 2 }, senses: { blindsight: 30, passivePerception: 12 }, languages: [],
    challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    traits: [
      { name: "Pack Tactics", text: "The shark has Advantage on an attack roll against a creature if at least one ally is within 5 feet of the creature and isn't Incapacitated." },
      { name: "Water Breathing", text: "The shark can breathe only underwater." },
    ],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 7 (2d4 + 2) Piercing damage." }],
  },
  {
    id: "rhinoceros", name: "Rhinoceros", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 45, hitDice: "6d10 + 12", initiative: { modifier: -1, score: 9 },
    speed: { walk: 40 }, stats: { str: 21, dex: 8, con: 15, int: 2, wis: 12, cha: 6 },
    senses: { passivePerception: 11 }, languages: [], challengeRating: "2", xp: 450, proficiencyBonus: 2,
    actions: [{ name: "Gore", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 14 (2d8 + 5) Piercing damage. After moving 20+ feet straight toward a Large or smaller target, it takes an extra 9 (2d8) Piercing damage and falls Prone." }],
  },
  {
    id: "riding-horse", name: "Riding Horse", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 11, hp: 13, hitDice: "2d10 + 2", initiative: { modifier: 1, score: 11 },
    speed: { walk: 60 }, stats: { str: 16, dex: 13, con: 12, int: 2, wis: 11, cha: 7 },
    senses: { passivePerception: 10 }, languages: [], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    actions: [{ name: "Hooves", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Bludgeoning damage." }],
  },
  {
    id: "saber-toothed-tiger", name: "Saber-Toothed Tiger", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 52, hitDice: "7d10 + 14", initiative: { modifier: 3, score: 13 },
    speed: { walk: 40 }, stats: { str: 18, dex: 17, con: 15, int: 3, wis: 12, cha: 8 },
    skills: { Perception: 3, Stealth: 7 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "2", xp: 450, proficiencyBonus: 2,
    actions: [{ name: "Rend", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 11 (2d6 + 4) Slashing damage. A Large or smaller target also falls Prone." }],
    bonusActions: [{ name: "Nimble Escape", text: "The tiger takes the Disengage or Hide action." }],
  },
  {
    id: "scorpion", name: "Scorpion", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 11, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 0, score: 10 },
    speed: { walk: 10 }, stats: { str: 2, dex: 11, con: 8, int: 1, wis: 8, cha: 2 },
    senses: { blindsight: 10, passivePerception: 9 }, languages: [], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    actions: [{ name: "Sting", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 1 Piercing damage plus 2 (1d4) Poison damage." }],
  },
  {
    id: "seahorse", name: "Seahorse", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 11, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 1, score: 11 },
    speed: { walk: 5, swim: 20 }, stats: { str: 1, dex: 12, con: 8, int: 1, wis: 10, cha: 2 },
    senses: { passivePerception: 10 }, languages: [], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Water Breathing", text: "The seahorse can breathe only underwater." }],
    actions: [{ name: "Ram", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 1 Bludgeoning damage." }],
  },
  {
    id: "spider", name: "Spider", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 12, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 2, score: 12 },
    speed: { walk: 20, climb: 20 }, stats: { str: 2, dex: 14, con: 8, int: 1, wis: 10, cha: 2 },
    skills: { Stealth: 4 }, senses: { darkvision: 30, passivePerception: 10 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [
      { name: "Spider Climb", text: "The spider can climb difficult surfaces, including along ceilings, without an ability check." },
      { name: "Web Walker", text: "The spider ignores movement restrictions caused by webs and knows the location of creatures touching the same web." },
    ],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 1 Piercing damage plus 2 (1d4) Poison damage." }],
  },
  {
    id: "swarm-of-bats", name: "Swarm of Bats", type: "Beast", subtype: "Swarm of Tiny Beasts", size: "Large", alignment: "Unaligned",
    armorClass: 12, hp: 11, hitDice: "2d10", initiative: { modifier: 2, score: 12 },
    speed: { walk: 5, fly: 30 }, stats: { str: 5, dex: 15, con: 10, int: 2, wis: 12, cha: 4 },
    damageResistances: ["Bludgeoning", "Piercing", "Slashing"],
    conditionImmunities: ["Charmed", "Frightened", "Grappled", "Paralyzed", "Petrified", "Prone", "Restrained", "Stunned"],
    senses: { blindsight: 60, passivePerception: 11 }, languages: [], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Swarm", text: "The swarm can share another creature's space, move through openings large enough for a Tiny bat, and can't regain Hit Points or gain Temporary Hit Points." }],
    actions: [{ name: "Bites", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (2d4) Piercing damage, or 2 (1d4) while Bloodied." }],
  },
  {
    id: "swarm-of-insects", name: "Swarm of Insects", type: "Beast", subtype: "Swarm of Tiny Beasts", size: "Medium", alignment: "Unaligned",
    armorClass: 11, hp: 19, hitDice: "3d8 + 6", initiative: { modifier: 1, score: 11 },
    speed: { walk: 20, climb: 20, notes: "Climb or Fly 20 ft. (GM's choice)" },
    stats: { str: 3, dex: 13, con: 14, int: 1, wis: 7, cha: 1 },
    damageResistances: ["Bludgeoning", "Piercing", "Slashing"],
    conditionImmunities: ["Charmed", "Frightened", "Grappled", "Paralyzed", "Petrified", "Prone", "Restrained", "Stunned"],
    senses: { blindsight: 30, passivePerception: 8 }, languages: [], challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    traits: [
      { name: "Spider Climb", text: "If the swarm has a Climb Speed, it can climb difficult surfaces and ceilings without an ability check." },
      { name: "Swarm", text: "The swarm can share another creature's space, move through openings large enough for a Tiny insect, and can't regain Hit Points or gain Temporary Hit Points." },
    ],
    actions: [{ name: "Bites", text: "Melee Attack Roll: +3, reach 5 ft. Hit: 6 (2d4 + 1) Poison damage, or 3 (1d4 + 1) while Bloodied." }],
  },
  {
    id: "swarm-of-piranhas", name: "Swarm of Piranhas", type: "Beast", subtype: "Swarm of Tiny Beasts", size: "Medium", alignment: "Unaligned",
    armorClass: 13, hp: 28, hitDice: "8d8 - 8", initiative: { modifier: 3, score: 13 },
    speed: { walk: 5, swim: 40 }, stats: { str: 13, dex: 16, con: 9, int: 1, wis: 7, cha: 2 },
    damageResistances: ["Bludgeoning", "Piercing", "Slashing"],
    conditionImmunities: ["Charmed", "Frightened", "Grappled", "Paralyzed", "Petrified", "Prone", "Restrained", "Stunned"],
    senses: { darkvision: 60, passivePerception: 8 }, languages: [], challengeRating: "1", xp: 200, proficiencyBonus: 2,
    traits: [
      { name: "Swarm", text: "The swarm can share another creature's space, move through openings large enough for a Tiny piranha, and can't regain Hit Points or gain Temporary Hit Points." },
      { name: "Water Breathing", text: "The swarm can breathe only underwater." },
    ],
    actions: [{ name: "Bites", text: "Melee Attack Roll: +5, with Advantage if the target doesn't have all its Hit Points, reach 5 ft. Hit: 8 (2d4 + 3) Piercing damage, or 5 (1d4 + 3) while Bloodied." }],
  },
  {
    id: "swarm-of-rats", name: "Swarm of Rats", type: "Beast", subtype: "Swarm of Tiny Beasts", size: "Medium", alignment: "Unaligned",
    armorClass: 10, hp: 14, hitDice: "4d8 - 4", initiative: { modifier: 0, score: 10 },
    speed: { walk: 30, climb: 30 }, stats: { str: 9, dex: 11, con: 9, int: 2, wis: 10, cha: 3 },
    savingThrows: { dex: 2 }, damageResistances: ["Bludgeoning", "Piercing", "Slashing"],
    conditionImmunities: ["Charmed", "Frightened", "Grappled", "Paralyzed", "Petrified", "Prone", "Restrained", "Stunned"],
    senses: { darkvision: 30, passivePerception: 10 }, languages: [], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Swarm", text: "The swarm can share another creature's space, move through openings large enough for a Tiny rat, and can't regain Hit Points or gain Temporary Hit Points." }],
    actions: [{ name: "Bites", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 5 (2d4) Piercing damage, or 2 (1d4) while Bloodied." }],
  },
  {
    id: "swarm-of-ravens", name: "Swarm of Ravens", type: "Beast", subtype: "Swarm of Tiny Beasts", size: "Medium", alignment: "Unaligned",
    armorClass: 12, hp: 11, hitDice: "2d8 + 2", initiative: { modifier: 2, score: 12 },
    speed: { walk: 10, fly: 50 }, stats: { str: 6, dex: 14, con: 12, int: 5, wis: 12, cha: 6 },
    skills: { Perception: 5 }, damageResistances: ["Bludgeoning", "Piercing", "Slashing"],
    conditionImmunities: ["Charmed", "Frightened", "Grappled", "Paralyzed", "Petrified", "Prone", "Restrained", "Stunned"],
    senses: { passivePerception: 15 }, languages: [], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Swarm", text: "The swarm can share another creature's space, move through openings large enough for a Tiny raven, and can't regain Hit Points or gain Temporary Hit Points." }],
    actions: [
      { name: "Beaks", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage, or 2 (1d4) while Bloodied." },
      { name: "Cacophony (Recharge 6)", text: "Wisdom Saving Throw: DC 10, one creature in the swarm's space. Failure: Deafened until the start of the swarm's next turn; while Deafened, the target has Disadvantage on ability checks and attack rolls." },
    ],
  },
  {
    id: "swarm-of-venomous-snakes", name: "Swarm of Venomous Snakes", type: "Beast", subtype: "Swarm of Tiny Beasts", size: "Medium", alignment: "Unaligned",
    armorClass: 14, hp: 36, hitDice: "8d8", initiative: { modifier: 4, score: 14 },
    speed: { walk: 30, swim: 30 }, stats: { str: 8, dex: 18, con: 11, int: 1, wis: 10, cha: 3 },
    damageResistances: ["Bludgeoning", "Piercing", "Slashing"],
    conditionImmunities: ["Charmed", "Frightened", "Grappled", "Paralyzed", "Petrified", "Prone", "Restrained", "Stunned"],
    senses: { blindsight: 10, passivePerception: 10 }, languages: [], challengeRating: "2", xp: 450, proficiencyBonus: 2,
    traits: [{ name: "Swarm", text: "The swarm can share another creature's space, move through openings large enough for a Tiny snake, and can't regain Hit Points or gain Temporary Hit Points." }],
    actions: [{ name: "Bites", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 8 (1d8 + 4) Piercing damage—or 6 (1d4 + 4) while Bloodied—plus 10 (3d6) Poison damage." }],
  },
  {
    id: "tiger", name: "Tiger", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 13, hp: 30, hitDice: "4d10 + 8", initiative: { modifier: 3, score: 13 },
    speed: { walk: 40 }, stats: { str: 17, dex: 16, con: 14, int: 3, wis: 12, cha: 8 },
    skills: { Perception: 3, Stealth: 7 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    actions: [{ name: "Rend", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Slashing damage. A Large or smaller target also falls Prone." }],
    bonusActions: [{ name: "Nimble Escape", text: "The tiger takes the Disengage or Hide action." }],
  },
  {
    id: "triceratops", name: "Triceratops", type: "Beast", subtype: "Dinosaur", size: "Huge", alignment: "Unaligned",
    armorClass: 14, hp: 114, hitDice: "12d12 + 36", initiative: { modifier: -1, score: 9 },
    speed: { walk: 50 }, stats: { str: 22, dex: 9, con: 17, int: 2, wis: 11, cha: 5 },
    senses: { passivePerception: 10 }, languages: [], challengeRating: "5", xp: 1800, proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The triceratops makes two Gore attacks." },
      { name: "Gore", text: "Melee Attack Roll: +9, reach 5 ft. Hit: 19 (2d12 + 6) Piercing damage. After moving 20+ feet straight toward a Huge or smaller target, it takes an extra 9 (2d8) Piercing damage and falls Prone." },
    ],
  },
  {
    id: "tyrannosaurus-rex", name: "Tyrannosaurus Rex", type: "Beast", subtype: "Dinosaur", size: "Huge", alignment: "Unaligned",
    armorClass: 13, hp: 136, hitDice: "13d12 + 52", initiative: { modifier: 3, score: 13 },
    speed: { walk: 50 }, stats: { str: 25, dex: 10, con: 19, int: 2, wis: 12, cha: 9 },
    savingThrows: { str: 10, wis: 4 }, skills: { Perception: 4 }, senses: { passivePerception: 14 }, languages: [],
    challengeRating: "8", xp: 3900, proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The tyrannosaurus makes one Bite attack and one Tail attack." },
      { name: "Bite", text: "Melee Attack Roll: +10, reach 10 ft. Hit: 33 (4d12 + 7) Piercing damage. A Large or smaller target is Grappled (escape DC 17) and Restrained while grappled, and can't be targeted by Tail." },
      { name: "Tail", text: "Melee Attack Roll: +10, reach 10 ft. Hit: 20 (3d8 + 7) Bludgeoning damage." },
    ],
  },
  {
    id: "venomous-snake", name: "Venomous Snake", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 12, hp: 2, hitDice: "1d4", initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, swim: 30 }, stats: { str: 2, dex: 15, con: 11, int: 1, wis: 10, cha: 3 },
    senses: { blindsight: 10, passivePerception: 10 }, languages: [], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 1 Piercing damage plus 2 (1d4) Poison damage." }],
  },
  {
    id: "vulture", name: "Vulture", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 10, hp: 5, hitDice: "1d8 + 1", initiative: { modifier: 0, score: 10 },
    speed: { walk: 10, fly: 50 }, stats: { str: 7, dex: 10, con: 13, int: 2, wis: 12, cha: 4 },
    skills: { Perception: 3 }, senses: { passivePerception: 13 }, languages: [], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The vulture has Advantage on an attack roll against a creature if at least one ally is within 5 feet of the creature and isn't Incapacitated." }],
    actions: [{ name: "Beak", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 2 (1d4) Piercing damage." }],
  },
  {
    id: "warhorse", name: "Warhorse", type: "Beast", size: "Large", alignment: "Unaligned",
    armorClass: 11, hp: 19, hitDice: "3d10 + 3", initiative: { modifier: 1, score: 11 },
    speed: { walk: 60 }, stats: { str: 18, dex: 12, con: 13, int: 2, wis: 12, cha: 7 },
    senses: { passivePerception: 11 }, languages: [], challengeRating: "1/2", xp: 100, proficiencyBonus: 2,
    actions: [{ name: "Hooves", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 9 (2d4 + 4) Bludgeoning damage. If the horse moved 20+ feet straight toward a Large or smaller target before the hit, the target also falls Prone." }],
  },
  {
    id: "weasel", name: "Weasel", type: "Beast", size: "Tiny", alignment: "Unaligned",
    armorClass: 13, hp: 1, hitDice: "1d4 - 1", initiative: { modifier: 3, score: 13 },
    speed: { walk: 30, climb: 30 }, stats: { str: 3, dex: 16, con: 8, int: 2, wis: 12, cha: 3 },
    skills: { Acrobatics: 5, Perception: 3, Stealth: 5 }, senses: { darkvision: 60, passivePerception: 13 }, languages: [],
    challengeRating: "0", xp: 10, proficiencyBonus: 2,
    actions: [{ name: "Bite", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 1 Piercing damage." }],
  },
  {
    id: "wolf", name: "Wolf", type: "Beast", size: "Medium", alignment: "Unaligned",
    armorClass: 12, hp: 11, hitDice: "2d8 + 2", initiative: { modifier: 2, score: 12 },
    speed: { walk: 40 }, stats: { str: 14, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    skills: { Perception: 5, Stealth: 4 }, senses: { darkvision: 60, passivePerception: 15 }, languages: [],
    challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The wolf has Advantage on an attack roll against a creature if at least one ally is within 5 feet of the creature and isn't Incapacitated." }],
    actions: [{ name: "Bite", text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage. A Medium or smaller target also falls Prone." }],
  },
];
