import type { MonsterDefinition } from "../monsterTypes";

/**
 * Complete Fey catalog from SRD 5.2.1.
 *
 * This work includes material from the System Reference Document 5.2.1
 * ("SRD 5.2.1") by Wizards of the Coast LLC, available at
 * https://www.dndbeyond.com/srd. The SRD 5.2.1 is licensed under the
 * Creative Commons Attribution 4.0 International License, available at
 * https://creativecommons.org/licenses/by/4.0/legalcode.
 */
export const fey: MonsterDefinition[] = [
  {
    id: "blink-dog",
    name: "Blink Dog",
    type: "Fey",
    size: "Medium",
    alignment: "Lawful Good",
    armorClass: 13,
    hp: 22,
    hitDice: "4d8 + 4",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 40 },
    stats: { str: 12, dex: 17, con: 12, int: 10, wis: 13, cha: 11 },
    skills: { Perception: 5, Stealth: 5 },
    senses: { darkvision: 60, passivePerception: 15 },
    languages: ["Blink Dog", "Understands Elvish and Sylvan but can't speak them"],
    challengeRating: "1/4",
    xp: 50,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Bite",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Piercing damage.",
      },
    ],
    bonusActions: [
      {
        name: "Teleport (Recharge 4–6)",
        text: "The dog teleports up to 40 feet to an unoccupied space it can see.",
      },
    ],
  },
  {
    id: "bugbear-stalker",
    name: "Bugbear Stalker",
    type: "Fey",
    subtype: "Goblinoid",
    size: "Medium",
    alignment: "Chaotic Evil",
    armorClass: 15,
    hp: 65,
    hitDice: "10d8 + 20",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30 },
    stats: { str: 17, dex: 14, con: 14, int: 11, wis: 12, cha: 11 },
    savingThrows: { con: 4, wis: 3 },
    skills: { Stealth: 6, Survival: 3 },
    gear: ["Chain Shirt", "Javelins (6)", "Morningstar"],
    senses: { darkvision: 60, passivePerception: 11 },
    languages: ["Common", "Goblin"],
    challengeRating: "3",
    xp: 700,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Abduct",
        text: "The bugbear needn't spend extra movement to move a creature it is grappling.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The bugbear makes two Javelin or Morningstar attacks.",
      },
      {
        name: "Javelin",
        text: "Melee or Ranged Attack Roll: +5, reach 10 ft. or range 30/120 ft. Hit: 13 (3d6 + 3) Piercing damage.",
      },
      {
        name: "Morningstar",
        text: "Melee Attack Roll: +5 (with Advantage if the target is Grappled by the bugbear), reach 10 ft. Hit: 12 (2d8 + 3) Piercing damage.",
      },
    ],
    bonusActions: [
      {
        name: "Quick Grapple",
        text: "Dexterity Saving Throw: DC 13, one Medium or smaller creature the bugbear can see within 10 feet. Failure: The target has the Grappled condition (escape DC 13).",
      },
    ],
  },
  {
    id: "bugbear-warrior",
    name: "Bugbear Warrior",
    type: "Fey",
    subtype: "Goblinoid",
    size: "Medium",
    alignment: "Chaotic Evil",
    armorClass: 14,
    hp: 33,
    hitDice: "6d8 + 6",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30 },
    stats: { str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9 },
    skills: { Stealth: 6, Survival: 2 },
    gear: ["Hide Armor", "Light Hammers (3)"],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: ["Common", "Goblin"],
    challengeRating: "1",
    xp: 200,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Abduct",
        text: "The bugbear needn't spend extra movement to move a creature it is grappling.",
      },
    ],
    actions: [
      {
        name: "Grab",
        text: "Melee Attack Roll: +4, reach 10 ft. Hit: 9 (2d6 + 2) Bludgeoning damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 12).",
      },
      {
        name: "Light Hammer",
        text: "Melee or Ranged Attack Roll: +4 (with Advantage if the target is Grappled by the bugbear), reach 10 ft. or range 20/60 ft. Hit: 9 (3d4 + 2) Bludgeoning damage.",
      },
    ],
  },
  {
    id: "centaur-trooper",
    name: "Centaur Trooper",
    type: "Fey",
    size: "Large",
    alignment: "Neutral Good",
    armorClass: 16,
    hp: 45,
    hitDice: "6d10 + 12",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 50 },
    stats: { str: 18, dex: 14, con: 14, int: 9, wis: 13, cha: 11 },
    skills: { Athletics: 6, Perception: 3 },
    gear: ["Breastplate", "Longbow", "Pike"],
    senses: { passivePerception: 13 },
    languages: ["Elvish", "Sylvan"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Multiattack",
        text: "The centaur makes two attacks, using Pike or Longbow in any combination.",
      },
      {
        name: "Pike",
        text: "Melee Attack Roll: +6, reach 10 ft. Hit: 9 (1d10 + 4) Piercing damage.",
      },
      {
        name: "Longbow",
        text: "Ranged Attack Roll: +4, range 150/600 ft. Hit: 6 (1d8 + 2) Piercing damage.",
      },
    ],
    bonusActions: [
      {
        name: "Trampling Charge (Recharge 5–6)",
        text: "The centaur moves up to its Speed without provoking Opportunity Attacks and can move through the spaces of Medium or smaller creatures. Each creature whose space the centaur enters is targeted once by the following effect. Strength Saving Throw: DC 14. Failure: 7 (1d6 + 4) Bludgeoning damage, and the target has the Prone condition.",
      },
    ],
  },
  {
    id: "dryad",
    name: "Dryad",
    type: "Fey",
    size: "Medium",
    alignment: "Neutral",
    armorClass: 16,
    hp: 22,
    hitDice: "5d8",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 30 },
    stats: { str: 10, dex: 12, con: 11, int: 14, wis: 15, cha: 18 },
    skills: { Perception: 4, Stealth: 5 },
    senses: { darkvision: 60, passivePerception: 14 },
    languages: ["Elvish", "Sylvan"],
    challengeRating: "1",
    xp: 200,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Magic Resistance",
        text: "The dryad has Advantage on saving throws against spells and other magical effects.",
      },
      {
        name: "Speak with Beasts and Plants",
        text: "The dryad can communicate with Beasts and Plants as if they shared a language.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The dryad makes one Vine Lash or Thorn Burst attack, and it can use Spellcasting to cast Charm Monster.",
      },
      {
        name: "Vine Lash",
        text: "Melee Attack Roll: +6, reach 10 ft. Hit: 8 (1d8 + 4) Slashing damage.",
      },
      {
        name: "Thorn Burst",
        text: "Ranged Attack Roll: +6, range 60 ft. Hit: 7 (1d6 + 4) Piercing damage.",
      },
      {
        name: "Spellcasting",
        text: "The dryad casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 14): At Will: Animal Friendship, Charm Monster (lasts 24 hours; ends early if the dryad casts the spell again), Druidcraft. 1/Day Each: Entangle, Pass without Trace.",
      },
    ],
    bonusActions: [
      {
        name: "Tree Stride",
        text: "If within 5 feet of a Large or bigger tree, the dryad teleports to an unoccupied space within 5 feet of a second Large or bigger tree that is within 60 feet of the previous tree.",
      },
    ],
  },
  {
    id: "goblin-boss",
    name: "Goblin Boss",
    type: "Fey",
    subtype: "Goblinoid",
    size: "Small",
    alignment: "Chaotic Neutral",
    armorClass: 17,
    hp: 21,
    hitDice: "6d6",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30 },
    stats: { str: 10, dex: 15, con: 10, int: 10, wis: 8, cha: 10 },
    skills: { Stealth: 6 },
    gear: ["Chain Shirt", "Scimitar", "Shield", "Shortbow"],
    senses: { darkvision: 60, passivePerception: 9 },
    languages: ["Common", "Goblin"],
    challengeRating: "1",
    xp: 200,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Multiattack",
        text: "The goblin makes two attacks, using Scimitar or Shortbow in any combination.",
      },
      {
        name: "Scimitar",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Slashing damage, plus 2 (1d4) Slashing damage if the attack roll had Advantage.",
      },
      {
        name: "Shortbow",
        text: "Ranged Attack Roll: +4, range 80/320 ft. Hit: 5 (1d6 + 2) Piercing damage, plus 2 (1d4) Piercing damage if the attack roll had Advantage.",
      },
    ],
    bonusActions: [
      {
        name: "Nimble Escape",
        text: "The goblin takes the Disengage or Hide action.",
      },
    ],
    reactions: [
      {
        name: "Redirect Attack",
        text: "Trigger: An attack roll targets the goblin while another goblin is within 5 feet of it. Response: The two goblins swap places, and the other goblin becomes the target instead.",
      },
    ],
  },
  {
    id: "goblin-minion",
    name: "Goblin Minion",
    type: "Fey",
    subtype: "Goblinoid",
    size: "Small",
    alignment: "Chaotic Neutral",
    armorClass: 12,
    hp: 7,
    hitDice: "2d6",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30 },
    stats: { str: 8, dex: 15, con: 10, int: 10, wis: 8, cha: 8 },
    skills: { Stealth: 6 },
    gear: ["Daggers (3)"],
    senses: { darkvision: 60, passivePerception: 9 },
    languages: ["Common", "Goblin"],
    challengeRating: "1/8",
    xp: 25,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Dagger",
        text: "Melee or Ranged Attack Roll: +4, reach 5 ft. or range 20/60 ft. Hit: 4 (1d4 + 2) Piercing damage.",
      },
    ],
    bonusActions: [
      {
        name: "Nimble Escape",
        text: "The goblin takes the Disengage or Hide action.",
      },
    ],
  },
  {
    id: "goblin-warrior",
    name: "Goblin Warrior",
    type: "Fey",
    subtype: "Goblinoid",
    size: "Small",
    alignment: "Chaotic Neutral",
    armorClass: 15,
    hp: 10,
    hitDice: "3d6",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30 },
    stats: { str: 8, dex: 15, con: 10, int: 10, wis: 8, cha: 8 },
    skills: { Stealth: 6 },
    gear: ["Leather Armor", "Scimitar", "Shield", "Shortbow"],
    senses: { darkvision: 60, passivePerception: 9 },
    languages: ["Common", "Goblin"],
    challengeRating: "1/4",
    xp: 50,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Scimitar",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Slashing damage, plus 2 (1d4) Slashing damage if the attack roll had Advantage.",
      },
      {
        name: "Shortbow",
        text: "Ranged Attack Roll: +4, range 80/320 ft. Hit: 5 (1d6 + 2) Piercing damage, plus 2 (1d4) Piercing damage if the attack roll had Advantage.",
      },
    ],
    bonusActions: [
      {
        name: "Nimble Escape",
        text: "The goblin takes the Disengage or Hide action.",
      },
    ],
  },
  {
    id: "green-hag",
    name: "Green Hag",
    type: "Fey",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 17,
    hp: 82,
    hitDice: "11d8 + 33",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 30, swim: 30 },
    stats: { str: 18, dex: 12, con: 16, int: 13, wis: 14, cha: 14 },
    skills: { Arcana: 5, Deception: 4, Perception: 4, Stealth: 3 },
    senses: { darkvision: 60, passivePerception: 14 },
    languages: ["Common", "Elvish", "Sylvan"],
    challengeRating: "3",
    xp: 700,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Amphibious",
        text: "The hag can breathe air and water.",
      },
      {
        name: "Coven Magic",
        text: "While within 30 feet of at least two hag allies, the hag can cast one of the following spells, requiring no Material components, using the spell's normal casting time, and using Intelligence as the spellcasting ability (spell save DC 11): Augury, Find Familiar, Identify, Locate Object, Scrying, or Unseen Servant. The hag must finish a Long Rest before using this trait to cast that spell again.",
      },
      {
        name: "Mimicry",
        text: "The hag can mimic animal sounds and humanoid voices. A creature that hears the sounds can tell they are imitations only with a successful DC 14 Wisdom (Insight) check.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The hag makes two Claw attacks.",
      },
      {
        name: "Claw",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 8 (1d8 + 4) Slashing damage plus 3 (1d6) Poison damage.",
      },
      {
        name: "Spellcasting",
        text: "The hag casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 12, +4 to hit with spell attacks): At Will: Dancing Lights, Disguise Self (24-hour duration), Invisibility (self only, and the hag leaves no tracks while Invisible), Minor Illusion, Ray of Sickness (level 3 version).",
      },
    ],
  },
  {
    id: "hobgoblin-captain",
    name: "Hobgoblin Captain",
    type: "Fey",
    subtype: "Goblinoid",
    size: "Medium",
    alignment: "Lawful Evil",
    armorClass: 17,
    hp: 58,
    hitDice: "9d8 + 18",
    initiative: { modifier: 4, score: 14 },
    speed: { walk: 30 },
    stats: { str: 15, dex: 14, con: 14, int: 12, wis: 10, cha: 13 },
    gear: ["Greatsword", "Half Plate Armor", "Longbow"],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: ["Common", "Goblin"],
    challengeRating: "3",
    xp: 700,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Aura of Authority",
        text: "While in a 10-foot Emanation originating from the hobgoblin, the hobgoblin and its allies have Advantage on attack rolls and saving throws, provided the hobgoblin doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The hobgoblin makes two attacks, using Greatsword or Longbow in any combination.",
      },
      {
        name: "Greatsword",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 9 (2d6 + 2) Slashing damage plus 3 (1d6) Poison damage.",
      },
      {
        name: "Longbow",
        text: "Ranged Attack Roll: +4, range 150/600 ft. Hit: 6 (1d8 + 2) Piercing damage plus 5 (2d4) Poison damage.",
      },
    ],
  },
  {
    id: "hobgoblin-warrior",
    name: "Hobgoblin Warrior",
    type: "Fey",
    subtype: "Goblinoid",
    size: "Medium",
    alignment: "Lawful Evil",
    armorClass: 18,
    hp: 11,
    hitDice: "2d8 + 2",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 30 },
    stats: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
    gear: ["Half Plate Armor", "Longbow", "Longsword", "Shield"],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: ["Common", "Goblin"],
    challengeRating: "1/2",
    xp: 100,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Pack Tactics",
        text: "The hobgoblin has Advantage on an attack roll against a creature if at least one of the hobgoblin's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Longsword",
        text: "Melee Attack Roll: +3, reach 5 ft. Hit: 12 (2d10 + 1) Slashing damage.",
      },
      {
        name: "Longbow",
        text: "Ranged Attack Roll: +3, range 150/600 ft. Hit: 5 (1d8 + 1) Piercing damage plus 7 (3d4) Poison damage.",
      },
    ],
  },
  {
    id: "satyr",
    name: "Satyr",
    type: "Fey",
    size: "Medium",
    alignment: "Chaotic Neutral",
    armorClass: 13,
    hp: 31,
    hitDice: "7d8",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 40 },
    stats: { str: 12, dex: 16, con: 11, int: 12, wis: 10, cha: 14 },
    skills: { Perception: 2, Performance: 6, Stealth: 5 },
    senses: { passivePerception: 12 },
    languages: ["Common", "Elvish", "Sylvan"],
    challengeRating: "1/2",
    xp: 100,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Magic Resistance",
        text: "The satyr has Advantage on saving throws against spells and other magical effects.",
      },
    ],
    actions: [
      {
        name: "Hooves",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Bludgeoning damage. If the target is a Medium or smaller creature, the satyr pushes the target up to 10 feet straight away from itself.",
      },
      {
        name: "Mockery",
        text: "Wisdom Saving Throw: DC 12, one creature the satyr can see within 90 feet. Failure: 5 (1d6 + 2) Psychic damage.",
      },
    ],
  },
  {
    id: "sea-hag",
    name: "Sea Hag",
    type: "Fey",
    size: "Medium",
    alignment: "Chaotic Evil",
    armorClass: 14,
    hp: 52,
    hitDice: "7d8 + 21",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 30, swim: 40 },
    stats: { str: 16, dex: 13, con: 16, int: 12, wis: 12, cha: 13 },
    senses: { darkvision: 60, passivePerception: 11 },
    languages: ["Common", "Giant", "Primordial (Aquan)"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Amphibious",
        text: "The hag can breathe air and water.",
      },
      {
        name: "Coven Magic",
        text: "While within 30 feet of at least two hag allies, the hag can cast one of the following spells, requiring no Material components, using the spell's normal casting time, and using Intelligence as the spellcasting ability (spell save DC 11): Augury, Find Familiar, Identify, Locate Object, Scrying, or Unseen Servant. The hag must finish a Long Rest before using this trait to cast that spell again.",
      },
      {
        name: "Vile Appearance",
        text: "Wisdom Saving Throw: DC 11, any Beast or Humanoid that starts its turn within 30 feet of the hag and can see the hag's true form. Failure: The target has the Frightened condition until the start of its next turn. Success: The target is immune to this hag's Vile Appearance for 24 hours.",
      },
    ],
    actions: [
      {
        name: "Claw",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Slashing damage.",
      },
      {
        name: "Death Glare (Recharge 5–6)",
        text: "Wisdom Saving Throw: DC 11, one Frightened creature the hag can see within 30 feet. Failure: 27 (6d8) Psychic damage. Success: Half damage.",
      },
      {
        name: "Illusory Appearance",
        text: "The hag casts Disguise Self, requiring no spell components and using Charisma as the spellcasting ability (spell save DC 11). The spell lasts until the hag ends it (no action required).",
      },
    ],
  },
  {
    id: "sprite",
    name: "Sprite",
    type: "Fey",
    size: "Tiny",
    alignment: "Neutral Good",
    armorClass: 15,
    hp: 10,
    hitDice: "4d4",
    initiative: { modifier: 4, score: 14 },
    speed: { walk: 10, fly: 40 },
    stats: { str: 3, dex: 18, con: 10, int: 14, wis: 13, cha: 11 },
    skills: { Perception: 3, Stealth: 8 },
    senses: { passivePerception: 13 },
    languages: ["Common", "Elvish", "Sylvan"],
    challengeRating: "1/4",
    xp: 50,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Needle Sword",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 6 (1d4 + 4) Piercing damage.",
      },
      {
        name: "Enchanting Bow",
        text: "Ranged Attack Roll: +6, range 40/160 ft. Hit: 1 Piercing damage, and the target has the Charmed condition until the start of the sprite's next turn.",
      },
      {
        name: "Heart Sight",
        text: "Charisma Saving Throw: DC 10, one creature within 5 feet the sprite can see (Celestials, Fiends, and Undead automatically fail the save). Failure: The sprite knows the target's emotions and alignment.",
      },
      {
        name: "Invisibility",
        text: "The sprite casts Invisibility on itself, requiring no spell components and using Charisma as the spellcasting ability.",
      },
    ],
  },
];
