import type { MonsterDefinition } from "../monsterTypes";

/**
 * Complete Fiend catalog from SRD 5.2.1.
 *
 * This work includes material from the System Reference Document 5.2.1
 * ("SRD 5.2.1") by Wizards of the Coast LLC, available at
 * https://www.dndbeyond.com/srd. The SRD 5.2.1 is licensed under the
 * Creative Commons Attribution 4.0 International License, available at
 * https://creativecommons.org/licenses/by/4.0/legalcode.
 */
export const fiends: MonsterDefinition[] = [
  {
    id: "balor", name: "Balor", type: "Fiend", subtype: "Demon", size: "Huge", alignment: "Chaotic Evil",
    armorClass: 19, hp: 287, hitDice: "23d12 + 138", initiative: { modifier: 12, score: 22 },
    speed: { walk: 40, fly: 80 },
    stats: { str: 26, dex: 15, con: 22, int: 20, wis: 16, cha: 22 },
    savingThrows: { str: 14, con: 12, wis: 9, cha: 12 },
    damageResistances: ["Cold", "Lightning"],
    damageImmunities: ["Fire", "Poison"],
    conditionImmunities: ["Poisoned"],
    senses: { truesight: 120, passivePerception: 13 },
    languages: ["Abyssal", "Telepathy 120 ft."],
    challengeRating: "19", xp: 22000, proficiencyBonus: 6,
    traits: [
      { name: "Demonic Restoration", text: "If the balor dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss." },
      { name: "Death Throes", text: "When the balor dies, it explodes. Dexterity Saving Throw: DC 20, each creature in a 30-foot Emanation originating from the balor. Failure: 70 (20d6) Fire damage. Success: Half damage." },
      { name: "Fire Aura", text: "At the end of each of the balor's turns, each creature in a 5-foot Emanation originating from it takes 10 (3d6) Fire damage." },
      { name: "Magic Resistance", text: "The balor has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The balor makes one Flame Whip attack and one Lightning Sword attack." },
      { name: "Flame Whip", text: "Melee Attack Roll: +14, reach 30 ft. Hit: 17 (2d8 + 8) Force damage plus 10 (3d6) Fire damage, and the target is pulled up to 25 feet toward the balor." },
      { name: "Lightning Sword", text: "Melee Attack Roll: +14, reach 10 ft. Hit: 21 (3d8 + 8) Slashing damage plus 13 (3d8) Lightning damage." },
      { name: "Teleport", text: "The balor teleports up to 120 feet to an unoccupied space it can see." },
    ],
  },
  {
    id: "barbed-devil", name: "Barbed Devil", type: "Fiend", subtype: "Devil", size: "Medium", alignment: "Lawful Evil",
    armorClass: 15, hp: 110, hitDice: "13d8 + 52", initiative: { modifier: 3, score: 13 },
    speed: { walk: 30, climb: 30 },
    stats: { str: 16, dex: 17, con: 18, int: 12, wis: 14, cha: 14 },
    savingThrows: { str: 6, con: 7, wis: 5, cha: 5 }, skills: { Deception: 5, Insight: 5, Perception: 8 },
    damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 120, passivePerception: 18, notes: "Darkvision is unimpeded by magical Darkness" },
    languages: ["Infernal", "Telepathy 120 ft."], challengeRating: "5", xp: 1800, proficiencyBonus: 3,
    traits: [
      { name: "Barbed Hide", text: "At the start of each of its turns, the devil deals 5 (1d10) Piercing damage to any creature it is grappling or any creature grappling it." },
      { name: "Diabolical Restoration", text: "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Magic Resistance", text: "The devil has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The devil makes one Claws attack and one Tail attack, or it makes two Hurl Flame attacks." },
      { name: "Claws", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 10 (2d6 + 3) Piercing damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 13) from both claws." },
      { name: "Tail", text: "Melee Attack Roll: +6, reach 10 ft. Hit: 14 (2d10 + 3) Slashing damage." },
      { name: "Hurl Flame", text: "Ranged Attack Roll: +5, range 150 ft. Hit: 17 (5d6) Fire damage. A flammable object that isn't being worn or carried starts burning." },
    ],
  },
  {
    id: "bearded-devil", name: "Bearded Devil", type: "Fiend", subtype: "Devil", size: "Medium", alignment: "Lawful Evil",
    armorClass: 13, hp: 58, hitDice: "9d8 + 18", initiative: { modifier: 2, score: 12 }, speed: { walk: 30 },
    stats: { str: 16, dex: 15, con: 15, int: 9, wis: 11, cha: 14 },
    savingThrows: { str: 5, con: 4, cha: 4 },
    damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Frightened", "Poisoned"],
    senses: { darkvision: 120, passivePerception: 10, notes: "Darkvision is unimpeded by magical Darkness" },
    languages: ["Infernal", "Telepathy 120 ft."], challengeRating: "3", xp: 700, proficiencyBonus: 2,
    traits: [
      { name: "Diabolical Restoration", text: "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Magic Resistance", text: "The devil has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The devil makes two attacks, using Glaive or Beard in any combination." },
      { name: "Glaive", text: "Melee Attack Roll: +5, reach 10 ft. Hit: 8 (1d10 + 3) Slashing damage, and the target receives an infernal wound. While wounded, the target loses Hit Points at the start of each of its turns until the wound closes." },
      { name: "Beard", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage plus Poison damage, and the target can become Poisoned." },
    ],
  },
  {
    id: "bone-devil", name: "Bone Devil", type: "Fiend", subtype: "Devil", size: "Large", alignment: "Lawful Evil",
    armorClass: 16, hp: 161, hitDice: "17d10 + 68", initiative: { modifier: 7, score: 17 }, speed: { walk: 40, fly: 40 },
    stats: { str: 18, dex: 16, con: 18, int: 13, wis: 14, cha: 16 },
    savingThrows: { str: 8, int: 5, wis: 6, cha: 7 }, skills: { Deception: 7, Insight: 6 },
    damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 120, passivePerception: 12, notes: "Darkvision is unimpeded by magical Darkness" },
    languages: ["Infernal", "Telepathy 120 ft."], challengeRating: "9", xp: 5000, proficiencyBonus: 4,
    traits: [
      { name: "Diabolical Restoration", text: "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Magic Resistance", text: "The devil has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The devil makes two Claw attacks and one Infernal Sting attack." },
      { name: "Claw", text: "Melee Attack Roll: +8, reach 10 ft. Hit: 13 (2d8 + 4) Slashing damage." },
      { name: "Infernal Sting", text: "Melee Attack Roll: +8, reach 10 ft. Hit: 15 (2d10 + 4) Piercing damage plus 18 (4d8) Poison damage, and the target has the Poisoned condition until the start of the devil's next turn. While Poisoned, the target can't regain Hit Points." },
    ],
  },
  {
    id: "chain-devil", name: "Chain Devil", type: "Fiend", subtype: "Devil", size: "Medium", alignment: "Lawful Evil",
    armorClass: 15, hp: 85, hitDice: "10d8 + 40", initiative: { modifier: 5, score: 15 }, speed: { walk: 30 },
    stats: { str: 18, dex: 15, con: 18, int: 11, wis: 12, cha: 14 },
    savingThrows: { con: 7, wis: 4 },
    damageResistances: ["Bludgeoning", "Cold", "Piercing", "Slashing"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 120, passivePerception: 11, notes: "Darkvision is unimpeded by magical Darkness" },
    languages: ["Infernal", "Telepathy 120 ft."], challengeRating: "8", xp: 3900, proficiencyBonus: 3,
    traits: [
      { name: "Diabolical Restoration", text: "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Magic Resistance", text: "The devil has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The devil makes two Chain attacks and uses Conjure Infernal Chain." },
      { name: "Chain", text: "Melee Attack Roll: +7, reach 10 ft. Hit: 11 (2d6 + 4) Slashing damage. A Large or smaller target has the Grappled condition (escape DC 14) and is Restrained until the grapple ends." },
      { name: "Conjure Infernal Chain", text: "Dexterity Saving Throw: DC 15, one creature the devil can see within 60 feet. Failure: 9 (2d4 + 4) Fire damage, and the target has the Restrained condition until the end of the devil's next turn. A Large or smaller target is also moved up to 30 feet straight toward the devil." },
    ],
    reactions: [
      { name: "Unnerving Gaze", text: "Trigger: A creature the devil can see starts its turn within 30 feet and can see the devil. Response—Wisdom Saving Throw: DC 15. Failure: The target has the Frightened condition until the end of its turn. Success: The target is immune to this devil's Unnerving Gaze for 24 hours." },
    ],
  },
  {
    id: "dretch", name: "Dretch", type: "Fiend", subtype: "Demon", size: "Small", alignment: "Chaotic Evil",
    armorClass: 11, hp: 18, hitDice: "4d6 + 4", initiative: { modifier: 0, score: 10 }, speed: { walk: 20 },
    stats: { str: 11, dex: 11, con: 12, int: 5, wis: 8, cha: 3 },
    damageResistances: ["Cold", "Fire", "Lightning"], damageImmunities: ["Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 60, passivePerception: 9 }, languages: ["Abyssal"], challengeRating: "1/4", xp: 50, proficiencyBonus: 2,
    traits: [{ name: "Demonic Restoration", text: "If the dretch dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss." }],
    actions: [
      { name: "Rend", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 5 (2d4) Slashing damage." },
      { name: "Fetid Cloud (1/Day)", text: "The dretch emits a disgusting cloud in a 10-foot Emanation. Creatures in the cloud must resist its poisonous stench or become Poisoned for a short time." },
    ],
  },
  {
    id: "erinyes", name: "Erinyes", type: "Fiend", subtype: "Devil", size: "Medium", alignment: "Lawful Evil",
    armorClass: 18, hp: 153, hitDice: "18d8 + 72", initiative: { modifier: 7, score: 17 }, speed: { walk: 30, fly: 60 },
    stats: { str: 18, dex: 16, con: 18, int: 14, wis: 14, cha: 18 },
    savingThrows: { str: 8, dex: 7, con: 8, wis: 6, cha: 8 },
    damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { truesight: 120, passivePerception: 12 }, languages: ["Infernal", "Telepathy 120 ft."],
    challengeRating: "12", xp: 8400, proficiencyBonus: 4,
    traits: [
      { name: "Diabolical Restoration", text: "If the erinyes dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Magic Resistance", text: "The erinyes has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The erinyes makes three attacks." },
      { name: "Fiendish Sword", text: "Melee Attack Roll: +8, reach 5 ft. Hit: Slashing damage plus Poison damage." },
      { name: "Hellish Bow", text: "Ranged Attack Roll: +7, long range. Hit: Piercing damage plus Poison damage." },
    ],
    reactions: [{ name: "Parry", text: "The erinyes adds to its AC against one melee attack that would hit it, provided it can see the attacker." }],
  },
  {
    id: "glabrezu", name: "Glabrezu", type: "Fiend", subtype: "Demon", size: "Large", alignment: "Chaotic Evil",
    armorClass: 17, hp: 157, hitDice: "15d10 + 75", initiative: { modifier: 2, score: 12 }, speed: { walk: 40 },
    stats: { str: 20, dex: 15, con: 21, int: 19, wis: 17, cha: 16 },
    savingThrows: { str: 9, con: 9, wis: 7, cha: 7 },
    damageResistances: ["Cold", "Fire", "Lightning"], damageImmunities: ["Poison"], conditionImmunities: ["Poisoned"],
    senses: { truesight: 120, passivePerception: 13 }, languages: ["Abyssal", "Telepathy 120 ft."],
    challengeRating: "9", xp: 5000, proficiencyBonus: 4,
    traits: [
      { name: "Demonic Restoration", text: "If the glabrezu dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss." },
      { name: "Magic Resistance", text: "The glabrezu has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The glabrezu makes multiple attacks with its pincers and fists." },
      { name: "Pincer", text: "Melee Attack Roll against a creature within reach. A Large or smaller creature can be Grappled by the pincer." },
      { name: "Fist", text: "Melee Attack Roll against a creature within reach, dealing Bludgeoning damage." },
      { name: "Spellcasting", text: "The glabrezu uses its innate demonic magic, requiring no Material components." },
    ],
  },
  {
    id: "hell-hound", name: "Hell Hound", type: "Fiend", size: "Medium", alignment: "Lawful Evil",
    armorClass: 15, hp: 45, hitDice: "7d8 + 14", initiative: { modifier: 1, score: 11 }, speed: { walk: 50 },
    stats: { str: 17, dex: 12, con: 14, int: 6, wis: 13, cha: 6 },
    skills: { Perception: 5 }, damageImmunities: ["Fire"],
    senses: { darkvision: 60, passivePerception: 15 }, languages: ["Understands Infernal but can't speak"],
    challengeRating: "3", xp: 700, proficiencyBonus: 2,
    traits: [{ name: "Pack Tactics", text: "The hound has Advantage on an attack roll against a creature if at least one of the hound's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition." }],
    actions: [
      { name: "Bite", text: "Melee Attack Roll against one target within 5 feet, dealing Piercing damage plus Fire damage." },
      { name: "Fire Breath (Recharge 5–6)", text: "Dexterity Saving Throw, each creature in a 15-foot Cone. Failure: Fire damage. Success: Half damage." },
    ],
  },
  {
    id: "hezrou", name: "Hezrou", type: "Fiend", subtype: "Demon", size: "Large", alignment: "Chaotic Evil",
    armorClass: 16, hp: 136, hitDice: "13d10 + 65", initiative: { modifier: 3, score: 13 }, speed: { walk: 30 },
    stats: { str: 19, dex: 17, con: 20, int: 5, wis: 12, cha: 13 },
    savingThrows: { str: 7, con: 8, wis: 4 },
    damageResistances: ["Cold", "Fire", "Lightning"], damageImmunities: ["Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 120, passivePerception: 11 }, languages: ["Abyssal", "Telepathy 120 ft."],
    challengeRating: "8", xp: 3900, proficiencyBonus: 3,
    traits: [
      { name: "Demonic Restoration", text: "If the hezrou dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss." },
      { name: "Magic Resistance", text: "The hezrou has Advantage on saving throws against spells and other magical effects." },
      { name: "Stench", text: "Creatures near the hezrou can become Poisoned by its supernatural stench." },
    ],
    actions: [
      { name: "Multiattack", text: "The hezrou makes three attacks." },
      { name: "Bite", text: "Melee Attack Roll against a creature within 5 feet, dealing Piercing damage." },
      { name: "Claw", text: "Melee Attack Roll against a creature within 5 feet, dealing Slashing damage." },
    ],
  },
  {
    id: "horned-devil", name: "Horned Devil", type: "Fiend", subtype: "Devil", size: "Large", alignment: "Lawful Evil",
    armorClass: 18, hp: 199, hitDice: "19d10 + 95", initiative: { modifier: 7, score: 17 }, speed: { walk: 30, fly: 60 },
    stats: { str: 22, dex: 17, con: 21, int: 12, wis: 16, cha: 18 },
    savingThrows: { str: 10, dex: 7, wis: 7, cha: 8 },
    damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 150, passivePerception: 13, notes: "Darkvision is unimpeded by magical Darkness" },
    languages: ["Infernal", "Telepathy 120 ft."], challengeRating: "11", xp: 7200, proficiencyBonus: 4,
    traits: [
      { name: "Diabolical Restoration", text: "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Magic Resistance", text: "The devil has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The devil makes three attacks, using Searing Fork or Hurl Flame in any combination. It can replace one attack with Infernal Tail." },
      { name: "Searing Fork", text: "Melee Attack Roll: +10, reach 10 ft. Hit: 15 (2d8 + 6) Piercing damage plus 9 (2d8) Fire damage." },
      { name: "Hurl Flame", text: "Ranged Attack Roll: +8, range 150 ft. Hit: 26 (5d8 + 4) Fire damage. A flammable object that isn't being worn or carried starts burning." },
      { name: "Infernal Tail", text: "Dexterity Saving Throw: DC 17, one creature within 10 feet. Failure: 10 (1d8 + 6) Necrotic damage, and the target receives an infernal wound. While wounded, it loses 10 (3d6) Hit Points at the start of each of its turns until the wound closes." },
    ],
  },
  {
    id: "ice-devil", name: "Ice Devil", type: "Fiend", subtype: "Devil", size: "Large", alignment: "Lawful Evil",
    armorClass: 18, hp: 228, hitDice: "24d10 + 96", initiative: { modifier: 7, score: 17 }, speed: { walk: 40 },
    stats: { str: 21, dex: 14, con: 18, int: 18, wis: 15, cha: 18 },
    savingThrows: { dex: 7, con: 9, wis: 7, cha: 9 }, skills: { Insight: 7, Perception: 7, Persuasion: 9 },
    damageImmunities: ["Cold", "Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { blindsight: 120, passivePerception: 17 }, languages: ["Infernal", "Telepathy 120 ft."],
    challengeRating: "14", xp: 11500, proficiencyBonus: 5,
    traits: [
      { name: "Diabolical Restoration", text: "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Magic Resistance", text: "The devil has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The devil makes three Ice Spear attacks. It can replace one attack with a Tail attack." },
      { name: "Ice Spear", text: "Melee or Ranged Attack Roll: +10, reach 5 ft. or range 30/120 ft. Hit: 14 (2d8 + 5) Piercing damage plus 10 (3d6) Cold damage. Until the end of its next turn, the target can't take a Bonus Action or Reaction, its Speed decreases by 10 feet, and it can move or take one action on its turn, not both." },
      { name: "Tail", text: "Melee Attack Roll: +10, reach 10 ft. Hit: 15 (3d6 + 5) Bludgeoning damage plus 18 (4d8) Cold damage." },
      { name: "Ice Wall (Recharge 6)", text: "The devil casts Wall of Ice (level 8 version), requiring no spell components and using Intelligence as the spellcasting ability (spell save DC 17)." },
    ],
  },
  {
    id: "imp", name: "Imp", type: "Fiend", subtype: "Devil", size: "Tiny", alignment: "Lawful Evil",
    armorClass: 13, hp: 21, hitDice: "6d4 + 6", initiative: { modifier: 3, score: 13 }, speed: { walk: 20, fly: 40 },
    stats: { str: 6, dex: 17, con: 13, int: 11, wis: 12, cha: 14 },
    skills: { Deception: 4, Insight: 3, Stealth: 5 }, damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 120, passivePerception: 11, notes: "Darkvision is unimpeded by magical Darkness" },
    languages: ["Common", "Infernal"], challengeRating: "1", xp: 200, proficiencyBonus: 2,
    traits: [{ name: "Magic Resistance", text: "The imp has Advantage on saving throws against spells and other magical effects." }],
    actions: [
      { name: "Sting", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage plus 7 (2d6) Poison damage." },
      { name: "Invisibility", text: "The imp casts Invisibility on itself, requiring no spell components and using Charisma as the spellcasting ability." },
      { name: "Shape-Shift", text: "The imp shape-shifts to resemble a rat (Speed 20 ft.), a raven (20 ft., Fly 60 ft.), or a spider (20 ft., Climb 20 ft.), or it returns to its true form. Its game statistics are the same in each form, except for its Speed." },
    ],
  },
  {
    id: "incubus", name: "Incubus", type: "Fiend", size: "Medium", alignment: "Neutral Evil",
    armorClass: 15, hp: 66, hitDice: "12d8 + 12", initiative: { modifier: 3, score: 13 }, speed: { walk: 30, fly: 60 },
    stats: { str: 8, dex: 17, con: 13, int: 15, wis: 12, cha: 20 },
    skills: { Deception: 9, Insight: 5, Perception: 5, Persuasion: 9, Stealth: 7 },
    damageResistances: ["Cold", "Fire", "Poison", "Psychic"],
    senses: { darkvision: 60, passivePerception: 15 }, languages: ["Abyssal", "Common", "Infernal", "Telepathy 60 ft."],
    challengeRating: "4", xp: 1100, proficiencyBonus: 2,
    traits: [{ name: "Succubus Form", text: "When the incubus finishes a Long Rest, it can shape-shift into a Succubus, using that stat block instead of this one. Any equipment it is wearing or carrying isn't transformed." }],
    actions: [
      { name: "Multiattack", text: "The incubus makes two Restless Touch attacks." },
      { name: "Restless Touch", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 15 (3d6 + 5) Psychic damage, and the target is cursed for 24 hours or until the incubus dies. Until the curse ends, the target gains no benefit from finishing Short Rests." },
      { name: "Spellcasting", text: "The incubus casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 15): At Will: Disguise Self, Etherealness. 1/Day Each: Dream, Hypnotic Pattern." },
    ],
    bonusActions: [{ name: "Nightmare (Recharge 6)", text: "Wisdom Saving Throw: DC 15, one creature within 60 feet. Failure: If the target has 20 Hit Points or fewer, it has the Unconscious condition for 1 hour, until it takes damage, or until awakened. Otherwise, it takes 18 (4d8) Psychic damage." }],
  },
  {
    id: "lamia", name: "Lamia", type: "Fiend", size: "Large", alignment: "Chaotic Evil",
    armorClass: 13, hp: 97, hitDice: "13d10 + 26", initiative: { modifier: 1, score: 11 }, speed: { walk: 40 },
    stats: { str: 16, dex: 13, con: 15, int: 14, wis: 15, cha: 16 },
    skills: { Deception: 7, Insight: 4, Stealth: 5 }, senses: { darkvision: 60, passivePerception: 12 },
    languages: ["Abyssal", "Common"], challengeRating: "4", xp: 1100, proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The lamia makes two Claw attacks. It can replace one attack with Corrupting Touch." },
      { name: "Claw", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Slashing damage plus 7 (2d6) Psychic damage." },
      { name: "Corrupting Touch", text: "Wisdom Saving Throw: DC 13, one creature within 5 feet. Failure: 13 (3d8) Psychic damage, and the target is cursed for 1 hour. Until the curse ends, the target has the Charmed and Poisoned conditions." },
      { name: "Spellcasting", text: "The lamia casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 13): At Will: Disguise Self, Minor Illusion. 1/Day Each: Geas, Major Image, Scrying." },
    ],
    bonusActions: [{ name: "Leap", text: "The lamia jumps up to 30 feet by spending 10 feet of movement." }],
  },
  {
    id: "lemure", name: "Lemure", type: "Fiend", subtype: "Devil", size: "Medium", alignment: "Lawful Evil",
    armorClass: 9, hp: 9, hitDice: "2d8", initiative: { modifier: -3, score: 7 }, speed: { walk: 20 },
    stats: { str: 10, dex: 5, con: 11, int: 1, wis: 11, cha: 3 },
    damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Charmed", "Frightened", "Poisoned"],
    senses: { darkvision: 120, passivePerception: 10, notes: "Darkvision is unimpeded by magical Darkness" },
    languages: ["Understands Infernal but can't speak"], challengeRating: "0", xp: 10, proficiencyBonus: 2,
    traits: [{ name: "Hellish Restoration", text: "If the lemure dies in the Nine Hells, it revives with all its Hit Points in 1d10 days unless it is killed by a creature under the effects of a Bless spell or its remains are sprinkled with Holy Water." }],
    actions: [{ name: "Vile Slime", text: "Melee Attack Roll: +2, reach 5 ft. Hit: 2 (1d4) Poison damage." }],
  },
  {
    id: "marilith", name: "Marilith", type: "Fiend", subtype: "Demon", size: "Large", alignment: "Chaotic Evil",
    armorClass: 18, hp: 189, hitDice: "18d10 + 90", initiative: { modifier: 9, score: 19 }, speed: { walk: 40 },
    stats: { str: 18, dex: 20, con: 20, int: 18, wis: 16, cha: 20 },
    savingThrows: { str: 9, dex: 10, con: 10, wis: 8, cha: 10 },
    damageResistances: ["Cold", "Fire", "Lightning"], damageImmunities: ["Poison"], conditionImmunities: ["Poisoned"],
    senses: { truesight: 120, passivePerception: 13 }, languages: ["Abyssal", "Telepathy 120 ft."],
    challengeRating: "16", xp: 15000, proficiencyBonus: 5,
    traits: [
      { name: "Demonic Restoration", text: "If the marilith dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss." },
      { name: "Magic Resistance", text: "The marilith has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The marilith makes multiple attacks with its blades and tail." },
      { name: "Fiendish Blade", text: "Melee Attack Roll against a creature within reach, dealing Slashing damage." },
      { name: "Constricting Tail", text: "Melee Attack Roll against a creature within reach. A Large or smaller target can be Grappled and Restrained." },
      { name: "Teleport", text: "The marilith teleports to an unoccupied space it can see." },
    ],
    reactions: [{ name: "Parry", text: "The marilith adds to its AC against an attack that would hit it, provided it can see the attacker." }],
  },
  {
    id: "nalfeshnee", name: "Nalfeshnee", type: "Fiend", subtype: "Demon", size: "Large", alignment: "Chaotic Evil",
    armorClass: 18, hp: 184, hitDice: "16d10 + 96", initiative: { modifier: 5, score: 15 }, speed: { walk: 20, fly: 30 },
    stats: { str: 21, dex: 10, con: 22, int: 19, wis: 12, cha: 15 },
    savingThrows: { con: 11, int: 9, wis: 6, cha: 7 },
    damageResistances: ["Cold", "Fire", "Lightning"], damageImmunities: ["Poison"], conditionImmunities: ["Frightened", "Poisoned"],
    senses: { truesight: 120, passivePerception: 11 }, languages: ["Abyssal", "Telepathy 120 ft."],
    challengeRating: "13", xp: 10000, proficiencyBonus: 5,
    traits: [
      { name: "Demonic Restoration", text: "If the nalfeshnee dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss." },
      { name: "Magic Resistance", text: "The nalfeshnee has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The nalfeshnee makes three Rend attacks." },
      { name: "Rend", text: "Melee Attack Roll: +10, reach 10 ft. Hit: 16 (2d10 + 5) Slashing damage plus 11 (2d10) Force damage." },
      { name: "Teleport", text: "The nalfeshnee teleports up to 120 feet to an unoccupied space it can see." },
    ],
    bonusActions: [{ name: "Horror Nimbus (Recharge 5–6)", text: "Wisdom Saving Throw: DC 15, each creature in a 15-foot Emanation. Failure: 28 (8d6) Psychic damage, and the target has the Frightened condition for 1 minute, until it takes damage, or until it ends its turn with the nalfeshnee out of line of sight. Success: The target is immune to this nalfeshnee's Horror Nimbus for 24 hours." }],
    reactions: [{ name: "Pursuit", text: "Trigger: Another creature the nalfeshnee can see ends its move within 120 feet. Response: The nalfeshnee uses Teleport, but its destination must be within 10 feet of the triggering creature." }],
  },
  {
    id: "night-hag", name: "Night Hag", type: "Fiend", size: "Medium", alignment: "Neutral Evil",
    armorClass: 17, hp: 112, hitDice: "15d8 + 45", initiative: { modifier: 5, score: 15 }, speed: { walk: 30 },
    stats: { str: 18, dex: 15, con: 16, int: 16, wis: 14, cha: 16 },
    skills: { Deception: 6, Insight: 5, Perception: 5, Stealth: 5 }, damageResistances: ["Cold", "Fire"], conditionImmunities: ["Charmed"],
    senses: { darkvision: 120, passivePerception: 15 }, languages: ["Abyssal", "Common", "Infernal", "Primordial"],
    challengeRating: "5", xp: 1800, proficiencyBonus: 3,
    traits: [
      { name: "Coven Magic", text: "While within 30 feet of at least two hag allies, the hag can cast certain coven spells, requiring no Material components and using Intelligence as the spellcasting ability (spell save DC 14)." },
      { name: "Magic Resistance", text: "The hag has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Claw", text: "Melee Attack Roll against one target within 5 feet, dealing Slashing damage plus Necrotic damage." },
      { name: "Spellcasting", text: "The hag uses innate magic requiring no Material components." },
    ],
    bonusActions: [{ name: "Shape-Shift", text: "The hag shape-shifts into a Small or Medium Humanoid, or it returns to its true form. Other than its size, its game statistics are unchanged." }],
  },
  {
    id: "nightmare", name: "Nightmare", type: "Fiend", size: "Large", alignment: "Neutral Evil",
    armorClass: 13, hp: 68, hitDice: "8d10 + 24", initiative: { modifier: 2, score: 12 }, speed: { walk: 60, fly: 90, hover: true },
    stats: { str: 18, dex: 15, con: 16, int: 10, wis: 13, cha: 15 }, damageImmunities: ["Fire"],
    senses: { passivePerception: 11 }, languages: ["Understands Abyssal, Common, and Infernal but can't speak"],
    challengeRating: "3", xp: 700, proficiencyBonus: 2,
    traits: [
      { name: "Confer Fire Resistance", text: "The nightmare can grant Resistance to Fire damage to a rider while it is on the nightmare." },
      { name: "Illumination", text: "The nightmare sheds Bright Light in a 10-foot radius and Dim Light for an additional 10 feet." },
    ],
    actions: [
      { name: "Hooves", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 13 (2d8 + 4) Bludgeoning damage plus 10 (3d6) Fire damage." },
      { name: "Ethereal Stride", text: "The nightmare and up to three willing creatures within 5 feet teleport to the Ethereal Plane from the Material Plane or vice versa." },
    ],
  },
  {
    id: "pit-fiend", name: "Pit Fiend", type: "Fiend", subtype: "Devil", size: "Large", alignment: "Lawful Evil",
    armorClass: 21, hp: 337, hitDice: "27d10 + 189", initiative: { modifier: 8, score: 18 }, speed: { walk: 30, fly: 60 },
    stats: { str: 26, dex: 14, con: 24, int: 22, wis: 18, cha: 24 },
    savingThrows: { dex: 8, wis: 10 }, skills: { Perception: 10, Persuasion: 19 },
    damageResistances: ["Cold"], damageImmunities: ["Fire", "Poison"], conditionImmunities: ["Poisoned"],
    senses: { truesight: 120, passivePerception: 20 }, languages: ["Infernal", "Telepathy 120 ft."],
    challengeRating: "20", xp: 25000, proficiencyBonus: 6,
    traits: [
      { name: "Diabolical Restoration", text: "If the pit fiend dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells." },
      { name: "Fear Aura", text: "The pit fiend emanates a 20-foot aura. Wisdom Saving Throw: DC 21, any enemy that starts its turn in the aura. Failure: Frightened until the start of its next turn. Success: Immune to this pit fiend's aura for 24 hours." },
      { name: "Legendary Resistance (4/Day)", text: "If the pit fiend fails a saving throw, it can choose to succeed instead." },
      { name: "Magic Resistance", text: "The pit fiend has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The pit fiend makes one Bite attack, two Devilish Claw attacks, and one Fiery Mace attack." },
      { name: "Bite", text: "Melee Attack Roll: +14, reach 10 ft. Hit: 18 (3d6 + 8) Piercing damage. A creature hit must make a DC 21 Constitution save or become Poisoned; while Poisoned it can't regain Hit Points and takes 21 (6d6) Poison damage at the start of each turn until it saves." },
      { name: "Devilish Claw", text: "Melee Attack Roll: +14, reach 10 ft. Hit: 26 (4d8 + 8) Necrotic damage." },
      { name: "Fiery Mace", text: "Melee Attack Roll: +14, reach 10 ft. Hit: 22 (4d6 + 8) Force damage plus 21 (6d6) Fire damage." },
      { name: "Hellfire Spellcasting (Recharge 4–6)", text: "The pit fiend casts Fireball (level 5 version) twice, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 21). It can replace one Fireball with Hold Monster (level 7 version) or Wall of Fire." },
    ],
  },
  {
    id: "quasit", name: "Quasit", type: "Fiend", subtype: "Demon", size: "Tiny", alignment: "Chaotic Evil",
    armorClass: 13, hp: 25, hitDice: "10d4", initiative: { modifier: 3, score: 13 }, speed: { walk: 40 },
    stats: { str: 5, dex: 17, con: 10, int: 7, wis: 10, cha: 10 }, skills: { Stealth: 5 },
    damageResistances: ["Cold", "Fire", "Lightning"], damageImmunities: ["Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 120, passivePerception: 10 }, languages: ["Abyssal", "Common"],
    challengeRating: "1", xp: 200, proficiencyBonus: 2,
    traits: [{ name: "Magic Resistance", text: "The quasit has Advantage on saving throws against spells and other magical effects." }],
    actions: [
      { name: "Rend", text: "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Slashing damage, and the target has the Poisoned condition until the start of the quasit's next turn." },
      { name: "Invisibility", text: "The quasit casts Invisibility on itself, requiring no spell components and using Charisma as the spellcasting ability." },
      { name: "Scare (1/Day)", text: "Wisdom Saving Throw: DC 10, one creature within 20 feet. Failure: The target has the Frightened condition and repeats the save at the end of each turn, ending the effect on a success." },
      { name: "Shape-Shift", text: "The quasit shape-shifts to resemble a bat, centipede, or toad, or returns to its true form. Its game statistics are the same except for its Speed." },
    ],
  },
  {
    id: "rakshasa", name: "Rakshasa", type: "Fiend", size: "Medium", alignment: "Lawful Evil",
    armorClass: 17, hp: 221, hitDice: "26d8 + 104", initiative: { modifier: 8, score: 18 }, speed: { walk: 40 },
    stats: { str: 14, dex: 17, con: 18, int: 13, wis: 16, cha: 20 },
    skills: { Deception: 10, Insight: 8, Perception: 8 },
    damageVulnerabilities: ["Piercing damage from weapons wielded by creatures under the effect of a Bless spell"],
    conditionImmunities: ["Charmed", "Frightened"], senses: { truesight: 60, passivePerception: 18 },
    languages: ["Common", "Infernal"], challengeRating: "13", xp: 10000, proficiencyBonus: 5,
    traits: [{ name: "Limited Magic Immunity", text: "The rakshasa can't be affected or detected by spells of level 6 or lower unless it wishes to be. It has Advantage on saving throws against all other spells and magical effects." }],
    actions: [
      { name: "Multiattack", text: "The rakshasa makes two Fiendish Claw attacks." },
      { name: "Fiendish Claw", text: "Melee Attack Roll against one target within 5 feet, dealing Slashing and Psychic damage and inflicting a magical curse." },
      { name: "Spellcasting", text: "The rakshasa casts innate spells using Charisma as its spellcasting ability and requiring no Material components." },
    ],
  },
  {
    id: "succubus", name: "Succubus", type: "Fiend", size: "Medium", alignment: "Neutral Evil",
    armorClass: 15, hp: 66, hitDice: "12d8 + 12", initiative: { modifier: 3, score: 13 }, speed: { walk: 30, fly: 60 },
    stats: { str: 8, dex: 17, con: 13, int: 15, wis: 12, cha: 20 },
    skills: { Deception: 9, Insight: 5, Perception: 5, Persuasion: 9, Stealth: 7 },
    damageResistances: ["Cold", "Fire", "Poison", "Psychic"],
    senses: { darkvision: 60, passivePerception: 15 }, languages: ["Abyssal", "Common", "Infernal", "Telepathy 60 ft."],
    challengeRating: "4", xp: 1100, proficiencyBonus: 2,
    traits: [{ name: "Incubus Form", text: "When the succubus finishes a Long Rest, it can shape-shift into an Incubus, using that stat block instead of this one." }],
    actions: [
      { name: "Multiattack", text: "The succubus makes one Fiendish Touch attack and uses Charm or Draining Kiss." },
      { name: "Fiendish Touch", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 16 (2d10 + 5) Psychic damage." },
      { name: "Charm", text: "The succubus casts Dominate Person (level 8 version), requiring no spell components and using Charisma as the spellcasting ability (spell save DC 15)." },
      { name: "Draining Kiss", text: "Constitution Saving Throw: DC 15, one creature Charmed by the succubus within 5 feet. Failure: 13 (3d8) Psychic damage. Success: Half damage. The target's Hit Point maximum decreases by the damage taken." },
    ],
    bonusActions: [{ name: "Shape-Shift", text: "The succubus shape-shifts into a Medium or Small Humanoid, or returns to its true form. Its statistics are unchanged except its Fly Speed is available only in its true form." }],
  },
  {
    id: "vrock", name: "Vrock", type: "Fiend", subtype: "Demon", size: "Large", alignment: "Chaotic Evil",
    armorClass: 15, hp: 104, hitDice: "11d10 + 44", initiative: { modifier: 2, score: 12 }, speed: { walk: 40, fly: 60 },
    stats: { str: 17, dex: 15, con: 18, int: 8, wis: 13, cha: 8 },
    savingThrows: { dex: 5, wis: 4, cha: 2 }, skills: { Perception: 4 },
    damageResistances: ["Cold", "Fire", "Lightning"], damageImmunities: ["Poison"], conditionImmunities: ["Poisoned"],
    senses: { darkvision: 120, passivePerception: 14 }, languages: ["Abyssal", "Telepathy 120 ft."],
    challengeRating: "6", xp: 2300, proficiencyBonus: 3,
    traits: [
      { name: "Demonic Restoration", text: "If the vrock dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss." },
      { name: "Magic Resistance", text: "The vrock has Advantage on saving throws against spells and other magical effects." },
    ],
    actions: [
      { name: "Multiattack", text: "The vrock makes two attacks." },
      { name: "Beak", text: "Melee Attack Roll against a creature within 5 feet, dealing Piercing damage." },
      { name: "Talons", text: "Melee Attack Roll against a creature within 5 feet, dealing Slashing damage." },
      { name: "Spores", text: "The vrock releases toxic spores in an Emanation around itself, poisoning creatures that fail a Constitution saving throw." },
    ],
    bonusActions: [{ name: "Stunning Screech (1/Day)", text: "The vrock emits a horrific screech. Creatures nearby that fail a Constitution saving throw have the Stunned condition until the end of the vrock's next turn." }],
  },
];
