import type { MonsterDefinition } from "../monsterTypes";

/**
 * Complete Giant catalog from SRD 5.2.1.
 *
 * This work includes material from the System Reference Document 5.2.1
 * ("SRD 5.2.1") by Wizards of the Coast LLC, available at
 * https://www.dndbeyond.com/srd. The SRD 5.2.1 is licensed under the
 * Creative Commons Attribution 4.0 International License, available at
 * https://creativecommons.org/licenses/by/4.0/legalcode.
 */
export const giants: MonsterDefinition[] = [
  {
    id: "cloud-giant",
    name: "Cloud Giant",
    type: "Giant",
    size: "Huge",
    alignment: "Neutral",
    armorClass: 14,
    hp: 200,
    hitDice: "16d12 + 96",
    initiative: { modifier: 4, score: 14 },
    speed: { walk: 40, fly: 20, hover: true },
    stats: { str: 27, dex: 10, con: 22, int: 12, wis: 16, cha: 16 },
    savingThrows: { str: 8, dex: 0, con: 10, int: 1, wis: 7, cha: 3 },
    skills: { Insight: 7, Perception: 11 },
    senses: { passivePerception: 21 },
    languages: ["Common", "Giant"],
    challengeRating: "9",
    xp: 5000,
    proficiencyBonus: 4,
    actions: [
      { name: "Multiattack", text: "The giant makes two attacks, using Thunderous Mace or Thundercloud in any combination. It can replace one attack with a use of Spellcasting to cast Fog Cloud." },
      { name: "Thunderous Mace", text: "Melee Attack Roll: +12, reach 10 ft. Hit: 21 (3d8 + 8) Bludgeoning damage plus 7 (2d6) Thunder damage." },
      { name: "Thundercloud", text: "Ranged Attack Roll: +12, range 240 ft. Hit: 18 (3d6 + 8) Thunder damage, and the target has the Incapacitated condition until the end of its next turn." },
      { name: "Spellcasting", text: "The giant casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 15): At Will: Detect Magic, Fog Cloud, Light. 1/Day Each: Control Weather, Gaseous Form, Telekinesis." },
    ],
    bonusActions: [
      { name: "Misty Step", text: "The giant casts the Misty Step spell, using the same spellcasting ability as Spellcasting." },
    ],
  },
  {
    id: "ettin",
    name: "Ettin",
    type: "Giant",
    size: "Large",
    alignment: "Chaotic Evil",
    armorClass: 12,
    hp: 85,
    hitDice: "10d10 + 30",
    initiative: { modifier: -1, score: 9 },
    speed: { walk: 40 },
    stats: { str: 21, dex: 8, con: 17, int: 6, wis: 10, cha: 8 },
    skills: { Perception: 4 },
    conditionImmunities: ["Blinded", "Charmed", "Deafened", "Frightened", "Stunned", "Unconscious"],
    gear: ["Battleaxe", "Morningstar"],
    senses: { darkvision: 60, passivePerception: 14 },
    languages: ["Giant"],
    challengeRating: "4",
    xp: 1100,
    proficiencyBonus: 2,
    actions: [
      { name: "Multiattack", text: "The ettin makes one Battleaxe attack and one Morningstar attack." },
      { name: "Battleaxe", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 14 (2d8 + 5) Slashing damage. If the target is a Large or smaller creature, it has the Prone condition." },
      { name: "Morningstar", text: "Melee Attack Roll: +7, reach 5 ft. Hit: 14 (2d8 + 5) Piercing damage, and the target has Disadvantage on the next attack roll it makes before the end of its next turn." },
    ],
  },
  {
    id: "fire-giant",
    name: "Fire Giant",
    type: "Giant",
    size: "Huge",
    alignment: "Lawful Evil",
    armorClass: 18,
    hp: 162,
    hitDice: "13d12 + 78",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 30 },
    stats: { str: 25, dex: 9, con: 23, int: 10, wis: 14, cha: 13 },
    savingThrows: { str: 7, dex: 3, con: 10, int: 0, wis: 2, cha: 5 },
    skills: { Athletics: 11, Perception: 6 },
    damageImmunities: ["Fire"],
    senses: { passivePerception: 16 },
    languages: ["Giant"],
    challengeRating: "9",
    xp: 5000,
    proficiencyBonus: 4,
    actions: [
      { name: "Multiattack", text: "The giant makes two attacks, using Flame Sword or Hammer Throw in any combination." },
      { name: "Flame Sword", text: "Melee Attack Roll: +11, reach 10 ft. Hit: 21 (4d6 + 7) Slashing damage plus 10 (3d6) Fire damage." },
      { name: "Hammer Throw", text: "Ranged Attack Roll: +11, range 60/240 ft. Hit: 23 (3d10 + 7) Bludgeoning damage plus 4 (1d8) Fire damage, and the target is pushed up to 15 feet straight away from the giant and has Disadvantage on the next attack roll it makes before the end of its next turn." },
    ],
  },
  {
    id: "frost-giant",
    name: "Frost Giant",
    type: "Giant",
    size: "Huge",
    alignment: "Neutral Evil",
    armorClass: 15,
    hp: 149,
    hitDice: "13d12 + 65",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 40 },
    stats: { str: 23, dex: 9, con: 21, int: 9, wis: 10, cha: 12 },
    savingThrows: { str: 6, dex: -1, con: 8, int: -1, wis: 3, cha: 4 },
    skills: { Athletics: 9, Perception: 3 },
    damageImmunities: ["Cold"],
    senses: { passivePerception: 13 },
    languages: ["Giant"],
    challengeRating: "8",
    xp: 3900,
    proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The giant makes two attacks, using Frost Axe or Great Bow in any combination." },
      { name: "Frost Axe", text: "Melee Attack Roll: +9, reach 10 ft. Hit: 19 (2d12 + 6) Slashing damage plus 9 (2d8) Cold damage." },
      { name: "Great Bow", text: "Ranged Attack Roll: +9, range 150/600 ft. Hit: 17 (2d10 + 6) Piercing damage plus 7 (2d6) Cold damage, and the target's Speed decreases by 10 feet until the end of its next turn." },
    ],
    bonusActions: [
      { name: "War Cry (Recharge 5–6)", text: "The giant or one creature of its choice that can see or hear it gains 16 (2d10 + 5) Temporary Hit Points and has Advantage on attack rolls until the start of the giant's next turn." },
    ],
  },
  {
    id: "hill-giant",
    name: "Hill Giant",
    type: "Giant",
    size: "Huge",
    alignment: "Chaotic Evil",
    armorClass: 13,
    hp: 105,
    hitDice: "10d12 + 40",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 40 },
    stats: { str: 21, dex: 8, con: 19, int: 5, wis: 9, cha: 6 },
    skills: { Perception: 2 },
    senses: { passivePerception: 12 },
    languages: ["Giant"],
    challengeRating: "5",
    xp: 1800,
    proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The giant makes two attacks, using Tree Club or Trash Lob in any combination." },
      { name: "Tree Club", text: "Melee Attack Roll: +8, reach 10 ft. Hit: 18 (3d8 + 5) Bludgeoning damage. If the target is a Large or smaller creature, it has the Prone condition." },
      { name: "Trash Lob", text: "Ranged Attack Roll: +8, range 60/240 ft. Hit: 16 (2d10 + 5) Bludgeoning damage, and the target has the Poisoned condition until the end of its next turn." },
    ],
  },
  {
    id: "ogre",
    name: "Ogre",
    type: "Giant",
    size: "Large",
    alignment: "Chaotic Evil",
    armorClass: 11,
    hp: 68,
    hitDice: "8d10 + 24",
    initiative: { modifier: -1, score: 9 },
    speed: { walk: 40 },
    stats: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    gear: ["Greatclub", "Javelins (3)"],
    senses: { darkvision: 60, passivePerception: 8 },
    languages: ["Common", "Giant"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    actions: [
      { name: "Greatclub", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 13 (2d8 + 4) Bludgeoning damage." },
      { name: "Javelin", text: "Melee or Ranged Attack Roll: +6, reach 5 ft. or range 30/120 ft. Hit: 11 (2d6 + 4) Piercing damage." },
    ],
  },
  {
    id: "stone-giant",
    name: "Stone Giant",
    type: "Giant",
    size: "Huge",
    alignment: "Neutral",
    armorClass: 17,
    hp: 126,
    hitDice: "11d12 + 55",
    initiative: { modifier: 5, score: 15 },
    speed: { walk: 40 },
    stats: { str: 23, dex: 15, con: 20, int: 10, wis: 12, cha: 9 },
    savingThrows: { str: 6, dex: 5, con: 8, int: 0, wis: 4, cha: -1 },
    skills: { Athletics: 12, Perception: 4, Stealth: 5 },
    senses: { darkvision: 60, passivePerception: 14 },
    languages: ["Giant"],
    challengeRating: "7",
    xp: 2900,
    proficiencyBonus: 3,
    actions: [
      { name: "Multiattack", text: "The giant makes two attacks, using Stone Club or Boulder in any combination." },
      { name: "Stone Club", text: "Melee Attack Roll: +9, reach 15 ft. Hit: 22 (3d10 + 6) Bludgeoning damage." },
      { name: "Boulder", text: "Ranged Attack Roll: +9, range 60/240 ft. Hit: 15 (2d8 + 6) Bludgeoning damage. If the target is a Large or smaller creature, it has the Prone condition." },
    ],
    reactions: [
      { name: "Deflect Missile (Recharge 5–6)", text: "Trigger: The giant is hit by a ranged attack roll and takes Bludgeoning, Piercing, or Slashing damage from it. Response: The giant reduces the damage it takes from the attack by 11 (1d10 + 6), and if that damage is reduced to 0, the giant can redirect some of the attack's force. Dexterity Saving Throw: DC 17, one creature the giant can see within 60 feet. Failure: 11 (1d10 + 6) Force damage." },
    ],
  },
  {
    id: "storm-giant",
    name: "Storm Giant",
    type: "Giant",
    size: "Huge",
    alignment: "Chaotic Good",
    armorClass: 16,
    hp: 230,
    hitDice: "20d12 + 100",
    initiative: { modifier: 7, score: 17 },
    speed: { walk: 50, fly: 25, hover: true, swim: 50 },
    stats: { str: 29, dex: 14, con: 20, int: 16, wis: 20, cha: 18 },
    savingThrows: { str: 14, dex: 2, con: 10, int: 3, wis: 10, cha: 9 },
    skills: { Arcana: 8, Athletics: 14, History: 8, Perception: 10 },
    damageResistances: ["Cold"],
    damageImmunities: ["Lightning", "Thunder"],
    senses: { darkvision: 120, truesight: 30, passivePerception: 20 },
    languages: ["Common", "Giant"],
    challengeRating: "13",
    xp: 10000,
    proficiencyBonus: 5,
    actions: [
      { name: "Multiattack", text: "The giant makes two attacks." },
      { name: "Storm Sword", text: "Melee Attack Roll: +14, reach 10 ft. Hit: 23 (4d6 + 9) Slashing damage plus Lightning damage." },
      { name: "Lightning Strike", text: "The giant calls down magical lightning against a creature it can see at range. The target makes a Dexterity saving throw, taking Lightning damage on a failed save or half as much on a successful one." },
    ],
  },
  {
    id: "troll",
    name: "Troll",
    type: "Giant",
    size: "Large",
    alignment: "Chaotic Evil",
    armorClass: 15,
    hp: 94,
    hitDice: "9d10 + 45",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 30 },
    stats: { str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7 },
    skills: { Perception: 5 },
    senses: { darkvision: 60, passivePerception: 15 },
    languages: ["Giant"],
    challengeRating: "5",
    xp: 1800,
    proficiencyBonus: 3,
    traits: [
      { name: "Loathsome Limbs (4/Day)", text: "If the troll ends any turn Bloodied and took 15+ Slashing damage during that turn, one of the troll's limbs is severed, falls into the troll's space, and becomes a Troll Limb. The limb acts immediately after the troll's turn. The troll has 1 Exhaustion level for each missing limb, and it grows replacement limbs the next time it regains Hit Points." },
      { name: "Regeneration", text: "The troll regains 15 Hit Points at the start of each of its turns. If the troll takes Acid or Fire damage, this trait doesn't function on the troll's next turn. The troll dies only if it starts its turn with 0 Hit Points and doesn't regenerate." },
    ],
    actions: [
      { name: "Multiattack", text: "The troll makes three Rend attacks." },
      { name: "Rend", text: "Melee Attack Roll: +7, reach 10 ft. Hit: 11 (2d6 + 4) Slashing damage." },
    ],
    bonusActions: [
      { name: "Charge", text: "The troll moves up to half its Speed straight toward an enemy it can see." },
    ],
  },
  {
    id: "troll-limb",
    name: "Troll Limb",
    type: "Giant",
    size: "Small",
    alignment: "Chaotic Evil",
    armorClass: 13,
    hp: 14,
    hitDice: "4d6",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 20 },
    stats: { str: 18, dex: 12, con: 10, int: 1, wis: 9, cha: 1 },
    senses: { darkvision: 60, passivePerception: 9 },
    languages: [],
    challengeRating: "1/2",
    xp: 100,
    proficiencyBonus: 2,
    traits: [
      { name: "Regeneration", text: "The limb regains 5 Hit Points at the start of each of its turns. If the limb takes Acid or Fire damage, this trait doesn't function on the limb's next turn. The limb dies only if it starts its turn with 0 Hit Points and doesn't regenerate." },
      { name: "Troll Spawn", text: "The limb uncannily has the same senses as a whole troll. If the limb isn't destroyed within 24 hours, roll 1d12. On a 12, the limb turns into a Troll. Otherwise, the limb withers away." },
    ],
    actions: [
      { name: "Rend", text: "Melee Attack Roll: +6, reach 5 ft. Hit: 9 (2d4 + 4) Slashing damage." },
    ],
  },
];
