import type { MonsterDefinition } from "../monsterTypes";

/**
 * Complete Undead catalog from SRD 5.2.1.
 *
 * This work includes material from the System Reference Document 5.2.1
 * ("SRD 5.2.1") by Wizards of the Coast LLC. The SRD 5.2.1 is licensed
 * under the Creative Commons Attribution 4.0 International License.
 */
export const undead: MonsterDefinition[] = [
  {
    id: "swarm-of-crawling-claws",
    name: "Swarm of Crawling Claws",
    type: "Undead",
    subtype: "Swarm of Tiny Undead",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 12,
    hp: 49,
    hitDice: "11d8",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, climb: 30 },
    stats: { str: 14, dex: 14, con: 11, int: 5, wis: 10, cha: 4 },
    damageResistances: ["Bludgeoning", "Piercing", "Slashing"],
    conditionImmunities: [
      "Charmed",
      "Frightened",
      "Grappled",
      "Paralyzed",
      "Petrified",
      "Prone",
      "Restrained",
      "Stunned",
    ],
    senses: { blindsight: 30, passivePerception: 10 },
    languages: ["Understands Common but can't speak"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Swarm",
        text: "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny crawling claw. The swarm can't regain Hit Points or gain Temporary Hit Points.",
      },
    ],
    actions: [
      {
        name: "Claws",
        text: "Melee Attack Roll: +4, reach 0 ft. Hit: 14 (4d6) Slashing damage, or 7 (2d6) Slashing damage if the swarm is Bloodied.",
      },
    ],
  },

  {
    id: "ghast",
    name: "Ghast",
    type: "Undead",
    size: "Medium",
    alignment: "Chaotic Evil",
    armorClass: 13,
    hp: 36,
    hitDice: "8d8",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 30 },
    stats: { str: 16, dex: 17, con: 10, int: 11, wis: 10, cha: 8 },
    savingThrows: { wis: 2 },
    damageResistances: ["Necrotic"],
    damageImmunities: ["Poison"],
    conditionImmunities: ["Charmed", "Exhaustion", "Poisoned"],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: ["Common"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Stench",
        text: "Constitution Saving Throw: DC 10, any creature that starts its turn in a 5-foot Emanation originating from the ghast. Failure: The target has the Poisoned condition until the start of its next turn. Success: The target is immune to this ghast's Stench for 24 hours.",
      },
    ],
    actions: [
      {
        name: "Bite",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Piercing damage plus 9 (2d8) Necrotic damage.",
      },
      {
        name: "Claw",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Slashing damage. If the target is a non-Undead creature, it makes a DC 10 Constitution saving throw. Failure: The target has the Paralyzed condition until the end of its next turn.",
      },
    ],
  },

  {
    id: "ghost",
    name: "Ghost",
    type: "Undead",
    size: "Medium",
    alignment: "Neutral",
    armorClass: 11,
    hp: 45,
    hitDice: "10d8",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 5, fly: 40, hover: true },
    stats: { str: 7, dex: 13, con: 10, int: 10, wis: 12, cha: 17 },
    damageResistances: [
      "Acid",
      "Bludgeoning",
      "Cold",
      "Fire",
      "Lightning",
      "Piercing",
      "Slashing",
      "Thunder",
    ],
    damageImmunities: ["Necrotic", "Poison"],
    conditionImmunities: [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Grappled",
      "Paralyzed",
      "Petrified",
      "Poisoned",
      "Prone",
      "Restrained",
    ],
    senses: { darkvision: 60, passivePerception: 11 },
    languages: ["Common", "One other language"],
    challengeRating: "4",
    xp: 1100,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Ethereal Sight",
        text: "The ghost can see 60 feet into the Ethereal Plane when it is on the Material Plane.",
      },
      {
        name: "Incorporeal Movement",
        text: "The ghost can move through other creatures and objects as if they were Difficult Terrain. It takes 5 (1d10) Force damage if it ends its turn inside an object.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The ghost makes two Withering Touch attacks.",
      },
      {
        name: "Withering Touch",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 19 (3d10 + 3) Necrotic damage.",
      },
      {
        name: "Etherealness",
        text: "The ghost casts the Etherealness spell, requiring no spell components and using Charisma as the spellcasting ability. The ghost is visible on the Material Plane while on the Border Ethereal and vice versa, but it can't affect or be affected by anything on the other plane.",
      },
      {
        name: "Horrific Visage",
        text: "Wisdom Saving Throw: DC 13, each creature in a 60-foot Cone that can see the ghost and isn't an Undead. Failure: 10 (2d6 + 3) Psychic damage, and the target has the Frightened condition until the start of the ghost's next turn. Success: The target is immune to this ghost's Horrific Visage for 24 hours.",
      },
      {
        name: "Possession (Recharge 6)",
        text: "Charisma Saving Throw: DC 13, one Humanoid the ghost can see within 5 feet. Failure: The target is possessed by the ghost. The ghost disappears, and the target has the Incapacitated condition and loses control of its body. The ghost controls the body while the target retains awareness. The possession lasts until the body drops to 0 Hit Points or the ghost leaves as a Bonus Action. Success: The target is immune to this ghost's Possession for 24 hours.",
      },
    ],
  },

  {
    id: "ghoul",
    name: "Ghoul",
    type: "Undead",
    size: "Medium",
    alignment: "Chaotic Evil",
    armorClass: 12,
    hp: 22,
    hitDice: "5d8",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30 },
    stats: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    damageImmunities: ["Poison"],
    conditionImmunities: ["Charmed", "Exhaustion", "Poisoned"],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: ["Common"],
    challengeRating: "1",
    xp: 200,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Multiattack",
        text: "The ghoul makes two Bite attacks.",
      },
      {
        name: "Bite",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage plus 3 (1d6) Necrotic damage.",
      },
      {
        name: "Claw",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 4 (1d4 + 2) Slashing damage. If the target is a creature that isn't an Undead or elf, it makes a DC 10 Constitution saving throw. Failure: The target has the Paralyzed condition until the end of its next turn.",
      },
    ],
  },

  {
    id: "lich",
    name: "Lich",
    type: "Undead",
    subtype: "Wizard",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 20,
    hp: 315,
    hitDice: "42d8 + 126",
    initiative: { modifier: 17, score: 27 },
    speed: { walk: 30 },
    stats: { str: 11, dex: 16, con: 16, int: 21, wis: 14, cha: 16 },
    savingThrows: { dex: 10, con: 10, int: 12, wis: 9 },
    skills: { Arcana: 19, History: 12, Insight: 9, Perception: 9 },
    damageResistances: ["Cold", "Lightning"],
    damageImmunities: ["Necrotic", "Poison"],
    conditionImmunities: [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Poisoned",
    ],
    gear: ["Component Pouch"],
    senses: { truesight: 120, passivePerception: 19 },
    languages: ["All"],
    challengeRating: "21",
    xp: 33000,
    proficiencyBonus: 7,
    traits: [
      {
        name: "Legendary Resistance (4/Day, or 5/Day in Lair)",
        text: "If the lich fails a saving throw, it can choose to succeed instead.",
      },
      {
        name: "Spirit Jar",
        text: "If destroyed, the lich reforms in 1d10 days if it has a spirit jar, reviving with all its Hit Points. The new body appears in an unoccupied space within the lich's lair.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The lich makes three attacks, using Eldritch Burst or Paralyzing Touch in any combination.",
      },
      {
        name: "Eldritch Burst",
        text: "Melee or Ranged Attack Roll: +12, reach 5 ft. or range 120 ft. Hit: 31 (4d12 + 5) Force damage.",
      },
      {
        name: "Paralyzing Touch",
        text: "Melee Attack Roll: +12, reach 5 ft. Hit: 15 (3d6 + 5) Cold damage, and the target has the Paralyzed condition until the start of the lich's next turn.",
      },
      {
        name: "Spellcasting",
        text: "The lich casts one of the following spells, using Intelligence as the spellcasting ability (spell save DC 20). At Will: Detect Magic, Detect Thoughts, Dispel Magic, Fireball (level 5 version), Invisibility, Lightning Bolt (level 5 version), Mage Hand, Prestidigitation. 2/Day Each: Animate Dead, Dimension Door, Plane Shift. 1/Day Each: Chain Lightning, Finger of Death, Power Word Kill, Scrying.",
      },
    ],
    reactions: [
      {
        name: "Protective Magic",
        text: "The lich casts Counterspell or Shield in response to the spell's trigger, using the same spellcasting ability as Spellcasting.",
      },
    ],
    legendaryActions: [
      {
        name: "Legendary Action Uses",
        text: "3 (4 in Lair). Immediately after another creature's turn, the lich can expend a use to take one of its legendary actions. It regains all expended uses at the start of each of its turns.",
      },
      {
        name: "Deathly Teleport",
        text: "The lich teleports up to 60 feet to an unoccupied space it can see, and each creature within 10 feet of the space it left takes 11 (2d10) Necrotic damage.",
      },
      {
        name: "Disrupt Life",
        text: "Constitution Saving Throw: DC 20, each creature that isn't an Undead in a 20-foot Emanation originating from the lich. Failure: 31 (9d6) Necrotic damage. Success: Half damage. The lich can't take this action again until the start of its next turn.",
      },
      {
        name: "Frightening Gaze",
        text: "The lich casts Fear, using the same spellcasting ability as Spellcasting. The lich can't take this action again until the start of its next turn.",
      },
    ],
  },

  {
    id: "mummy",
    name: "Mummy",
    type: "Undead",
    size: "Medium",
    alignment: "Lawful Evil",
    armorClass: 11,
    hp: 58,
    hitDice: "9d8 + 18",
    initiative: { modifier: -1, score: 9 },
    speed: { walk: 20 },
    stats: { str: 16, dex: 8, con: 15, int: 6, wis: 12, cha: 12 },
    savingThrows: { wis: 3 },
    damageVulnerabilities: ["Fire"],
    damageImmunities: ["Necrotic", "Poison"],
    conditionImmunities: [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Poisoned",
    ],
    senses: { darkvision: 60, passivePerception: 11 },
    languages: ["Common", "Two other languages"],
    challengeRating: "3",
    xp: 700,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Multiattack",
        text: "The mummy makes two Rotting Fist attacks and uses Dreadful Glare.",
      },
      {
        name: "Rotting Fist",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 8 (1d10 + 3) Bludgeoning damage plus 10 (3d6) Necrotic damage. If the target is a creature, it is cursed. While cursed, the target can't regain Hit Points, its Hit Point maximum doesn't return to normal when finishing a Long Rest, and its Hit Point maximum decreases by 10 (3d6) every 24 hours. A creature dies and turns to dust if reduced to 0 Hit Points by this attack.",
      },
      {
        name: "Dreadful Glare",
        text: "Wisdom Saving Throw: DC 11, one creature the mummy can see within 60 feet. Failure: The target has the Frightened condition until the end of the mummy's next turn. Success: The target is immune to this mummy's Dreadful Glare for 24 hours.",
      },
    ],
  },

  {
    id: "mummy-lord",
    name: "Mummy Lord",
    type: "Undead",
    subtype: "Cleric",
    size: "Medium",
    alignment: "Lawful Evil",
    armorClass: 17,
    hp: 187,
    hitDice: "25d8 + 75",
    initiative: { modifier: 10, score: 20 },
    speed: { walk: 30 },
    stats: { str: 18, dex: 10, con: 17, int: 11, wis: 19, cha: 16 },
    savingThrows: { int: 5, wis: 9 },
    skills: { History: 5, Perception: 9, Religion: 5 },
    damageVulnerabilities: ["Fire"],
    damageImmunities: ["Necrotic", "Poison"],
    conditionImmunities: [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Poisoned",
    ],
    senses: { truesight: 60, passivePerception: 19 },
    languages: ["Common", "Three other languages"],
    challengeRating: "15",
    xp: 13000,
    proficiencyBonus: 5,
    traits: [
      {
        name: "Legendary Resistance (3/Day, or 4/Day in Lair)",
        text: "If the mummy fails a saving throw, it can choose to succeed instead.",
      },
      {
        name: "Magic Resistance",
        text: "The mummy has Advantage on saving throws against spells and other magical effects.",
      },
      {
        name: "Undead Restoration",
        text: "If destroyed, the mummy gains a new body in 24 hours if its heart is intact, reviving with all its Hit Points. The new body appears in an unoccupied space within the mummy's lair. The heart is a Tiny object that has AC 17, HP 10, and Immunity to all damage except Fire.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The mummy makes one Rotting Fist or Channel Negative Energy attack, and it uses Dreadful Glare.",
      },
      {
        name: "Rotting Fist",
        text: "Melee Attack Roll: +9, reach 5 ft. Hit: 15 (2d10 + 4) Bludgeoning damage plus 10 (3d6) Necrotic damage. If the target is a creature, it is cursed. While cursed, the target can't regain Hit Points, it gains no benefit from finishing a Long Rest, and its Hit Point maximum decreases by 10 (3d6) every 24 hours. A creature dies and turns to dust if reduced to 0 Hit Points by this attack.",
      },
      {
        name: "Channel Negative Energy",
        text: "Ranged Attack Roll: +9, range 60 ft. Hit: 25 (6d6 + 4) Necrotic damage.",
      },
      {
        name: "Dreadful Glare",
        text: "Wisdom Saving Throw: DC 17, one creature the mummy can see within 60 feet. Failure: 25 (6d6 + 4) Psychic damage, and the target has the Paralyzed condition until the end of the mummy's next turn.",
      },
      {
        name: "Spellcasting",
        text: "The mummy casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 17, +9 to hit with spell attacks). At Will: Dispel Magic, Thaumaturgy. 1/Day Each: Animate Dead, Harm, Insect Plague (level 7 version).",
      },
    ],
    reactions: [
      {
        name: "Whirlwind of Sand",
        text: "Trigger: The mummy is hit by an attack roll. Response: The mummy adds 2 to its AC against the attack, possibly causing the attack to miss, and teleports up to 60 feet to an unoccupied space it can see. Each creature of its choice within 5 feet of its destination has the Blinded condition until the end of the mummy's next turn.",
      },
    ],
    legendaryActions: [
      {
        name: "Legendary Action Uses",
        text: "3 (4 in Lair). Immediately after another creature's turn, the mummy can expend a use to take one of its legendary actions. It regains all expended uses at the start of each of its turns.",
      },
      {
        name: "Dread Command",
        text: "The mummy casts Command (level 2 version), using the same spellcasting ability as Spellcasting. The mummy can't take this action again until the start of its next turn.",
      },
      {
        name: "Glare",
        text: "The mummy uses Dreadful Glare. The mummy can't take this action again until the start of its next turn.",
      },
      {
        name: "Necrotic Strike",
        text: "The mummy makes one Rotting Fist or Channel Negative Energy attack.",
      },
    ],
  },

  {
    id: "shadow",
    name: "Shadow",
    type: "Undead",
    size: "Medium",
    alignment: "Chaotic Evil",
    armorClass: 12,
    hp: 27,
    hitDice: "5d8 + 5",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 40 },
    stats: { str: 6, dex: 14, con: 13, int: 6, wis: 10, cha: 8 },
    skills: { Stealth: 6 },
    damageVulnerabilities: ["Radiant"],
    damageResistances: ["Acid", "Cold", "Fire", "Lightning", "Thunder"],
    damageImmunities: ["Necrotic", "Poison"],
    conditionImmunities: [
      "Exhaustion",
      "Frightened",
      "Grappled",
      "Paralyzed",
      "Petrified",
      "Poisoned",
      "Prone",
      "Restrained",
      "Unconscious",
    ],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: [],
    challengeRating: "1/2",
    xp: 100,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Amorphous",
        text: "The shadow can move through a space as narrow as 1 inch without expending extra movement to do so.",
      },
      {
        name: "Sunlight Weakness",
        text: "While in sunlight, the shadow has Disadvantage on D20 Tests.",
      },
    ],
    actions: [
      {
        name: "Draining Swipe",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Necrotic damage, and the target's Strength score decreases by 1d4. The target dies if this reduces that score to 0. If a Humanoid is slain by this attack, a Shadow rises from the corpse 1d4 hours later.",
      },
    ],
    bonusActions: [
      {
        name: "Shadow Stealth",
        text: "While in Dim Light or Darkness, the shadow takes the Hide action.",
      },
    ],
  },

  {
    id: "skeleton",
    name: "Skeleton",
    type: "Undead",
    size: "Medium",
    alignment: "Lawful Evil",
    armorClass: 14,
    hp: 13,
    hitDice: "2d8 + 4",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 30 },
    stats: { str: 10, dex: 16, con: 15, int: 6, wis: 8, cha: 5 },
    damageVulnerabilities: ["Bludgeoning"],
    damageImmunities: ["Poison"],
    conditionImmunities: ["Exhaustion", "Poisoned"],
    gear: ["Shortbow", "Shortsword"],
    senses: { darkvision: 60, passivePerception: 9 },
    languages: ["Understands Common plus one other language but can't speak"],
    challengeRating: "1/4",
    xp: 50,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Shortsword",
        text: "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage.",
      },
      {
        name: "Shortbow",
        text: "Ranged Attack Roll: +5, range 80/320 ft. Hit: 6 (1d6 + 3) Piercing damage.",
      },
    ],
  },

  {
    id: "warhorse-skeleton",
    name: "Warhorse Skeleton",
    type: "Undead",
    size: "Large",
    alignment: "Lawful Evil",
    armorClass: 13,
    hp: 22,
    hitDice: "3d10 + 6",
    initiative: { modifier: 1, score: 11 },
    speed: { walk: 60 },
    stats: { str: 18, dex: 12, con: 15, int: 2, wis: 8, cha: 5 },
    damageVulnerabilities: ["Bludgeoning"],
    damageImmunities: ["Poison"],
    conditionImmunities: ["Exhaustion", "Poisoned"],
    senses: { darkvision: 60, passivePerception: 9 },
    languages: [],
    challengeRating: "1/2",
    xp: 100,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Hooves",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 7 (1d6 + 4) Bludgeoning damage. If the target is a Large or smaller creature and the skeleton moved 20+ feet straight toward it immediately before the hit, the target has the Prone condition.",
      },
    ],
  },

  {
    id: "minotaur-skeleton",
    name: "Minotaur Skeleton",
    type: "Undead",
    size: "Large",
    alignment: "Lawful Evil",
    armorClass: 12,
    hp: 45,
    hitDice: "6d10 + 12",
    initiative: { modifier: 0, score: 10 },
    speed: { walk: 40 },
    stats: { str: 18, dex: 11, con: 15, int: 6, wis: 8, cha: 5 },
    damageVulnerabilities: ["Bludgeoning"],
    damageImmunities: ["Poison"],
    conditionImmunities: ["Exhaustion", "Poisoned"],
    senses: { darkvision: 60, passivePerception: 9 },
    languages: ["Understands Abyssal but can't speak"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    actions: [
      {
        name: "Gore",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 11 (2d6 + 4) Piercing damage. If the target is a Large or smaller creature and the skeleton moved 20+ feet straight toward it immediately before the hit, the target takes an extra 9 (2d8) Piercing damage and has the Prone condition.",
      },
      {
        name: "Slam",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 15 (2d10 + 4) Bludgeoning damage.",
      },
    ],
  },

  {
    id: "specter",
    name: "Specter",
    type: "Undead",
    size: "Medium",
    alignment: "Chaotic Evil",
    armorClass: 12,
    hp: 22,
    hitDice: "5d8",
    initiative: { modifier: 2, score: 12 },
    speed: { walk: 30, fly: 50, hover: true },
    stats: { str: 1, dex: 14, con: 11, int: 10, wis: 10, cha: 11 },
    damageResistances: [
      "Acid",
      "Bludgeoning",
      "Cold",
      "Fire",
      "Lightning",
      "Piercing",
      "Slashing",
      "Thunder",
    ],
    damageImmunities: ["Necrotic", "Poison"],
    conditionImmunities: [
      "Charmed",
      "Exhaustion",
      "Grappled",
      "Paralyzed",
      "Petrified",
      "Poisoned",
      "Prone",
      "Restrained",
      "Unconscious",
    ],
    senses: { darkvision: 60, passivePerception: 10 },
    languages: ["Understands Common plus one other language but can't speak"],
    challengeRating: "1",
    xp: 200,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Incorporeal Movement",
        text: "The specter can move through other creatures and objects as if they were Difficult Terrain. It takes 5 (1d10) Force damage if it ends its turn inside an object.",
      },
      {
        name: "Sunlight Sensitivity",
        text: "While in sunlight, the specter has Disadvantage on ability checks and attack rolls.",
      },
    ],
    actions: [
      {
        name: "Life Drain",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 7 (2d6) Necrotic damage. If the target is a creature, its Hit Point maximum decreases by an amount equal to the damage taken.",
      },
    ],
  },

  {
    id: "vampire-spawn",
    name: "Vampire Spawn",
    type: "Undead",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 16,
    hp: 90,
    hitDice: "12d8 + 36",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 30 },
    stats: { str: 16, dex: 16, con: 16, int: 11, wis: 10, cha: 12 },
    savingThrows: { dex: 6, wis: 3 },
    skills: { Perception: 3, Stealth: 6 },
    damageResistances: ["Necrotic"],
    senses: { darkvision: 60, passivePerception: 13 },
    languages: ["Common", "One other language"],
    challengeRating: "5",
    xp: 1800,
    proficiencyBonus: 3,
    traits: [
      {
        name: "Spider Climb",
        text: "The vampire can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
      {
        name: "Vampire Weakness",
        text: "Forbiddance: The vampire can't enter a residence without an invitation from an occupant. Running Water: The vampire takes 20 Acid damage if it ends its turn in running water. Stake to the Heart: The vampire is destroyed if a weapon that deals Piercing damage is driven into its heart while it has the Incapacitated condition. Sunlight: The vampire takes 20 Radiant damage if it starts its turn in sunlight; while in sunlight, it has Disadvantage on attack rolls and ability checks.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The vampire makes two Claw attacks and uses Bite.",
      },
      {
        name: "Claw",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 8 (2d4 + 3) Slashing damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 13) from one of two claws.",
      },
      {
        name: "Bite",
        text: "Constitution Saving Throw: DC 14, one creature within 5 feet that is willing or that has the Grappled, Incapacitated, or Restrained condition. Failure: 5 (1d4 + 3) Piercing damage plus 10 (3d6) Necrotic damage. The target's Hit Point maximum decreases by an amount equal to the Necrotic damage taken, and the vampire regains Hit Points equal to that amount.",
      },
    ],
    bonusActions: [
      {
        name: "Deathless Agility",
        text: "The vampire takes the Dash or Disengage action.",
      },
    ],
  },

  {
    id: "vampire",
    name: "Vampire",
    type: "Undead",
    size: "Medium",
    alignment: "Lawful Evil",
    armorClass: 16,
    hp: 195,
    hitDice: "23d8 + 92",
    initiative: { modifier: 14, score: 24 },
    speed: { walk: 40, climb: 40 },
    stats: { str: 18, dex: 18, con: 18, int: 17, wis: 15, cha: 18 },
    savingThrows: { dex: 9, con: 9, wis: 7, cha: 9 },
    skills: { Perception: 7, Stealth: 9 },
    damageResistances: ["Necrotic"],
    senses: { darkvision: 120, passivePerception: 17 },
    languages: ["Common", "Two other languages"],
    challengeRating: "13",
    xp: 10000,
    proficiencyBonus: 5,
    traits: [
      {
        name: "Legendary Resistance (3/Day, or 4/Day in Lair)",
        text: "If the vampire fails a saving throw, it can choose to succeed instead.",
      },
      {
        name: "Misty Escape",
        text: "If the vampire drops to 0 Hit Points outside its resting place, it uses Shape-Shift to become mist (no action required). If it can't use Shape-Shift, it is destroyed. While it has 0 Hit Points in mist form, it must reach its resting place within 2 hours or be destroyed. Once there, it returns to vampire form, has the Paralyzed condition until it regains any Hit Points, and regains 1 Hit Point after spending 1 hour there.",
      },
      {
        name: "Spider Climb",
        text: "The vampire can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
      {
        name: "Vampire Weakness",
        text: "Forbiddance: The vampire can't enter a residence without an invitation from an occupant. Running Water: The vampire takes 20 Acid damage if it ends its turn in running water. Stake to the Heart: If a weapon that deals Piercing damage is driven into the vampire's heart while it has the Incapacitated condition in its resting place, it has the Paralyzed condition until the weapon is removed. Sunlight: The vampire takes 20 Radiant damage if it starts its turn in sunlight; while in sunlight, it has Disadvantage on attack rolls and ability checks.",
      },
    ],
    actions: [
      {
        name: "Multiattack (Vampire Form Only)",
        text: "The vampire makes two Grave Strike attacks and uses Bite.",
      },
      {
        name: "Grave Strike (Vampire Form Only)",
        text: "Melee Attack Roll: +9, reach 5 ft. Hit: 8 (1d8 + 4) Bludgeoning damage plus 7 (2d6) Necrotic damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 14) from one of two hands.",
      },
      {
        name: "Bite (Bat or Vampire Form Only)",
        text: "Constitution Saving Throw: DC 17, one creature within 5 feet that is willing or that has the Grappled, Incapacitated, or Restrained condition. Failure: 6 (1d4 + 4) Piercing damage plus 13 (3d8) Necrotic damage. The target's Hit Point maximum decreases by an amount equal to the Necrotic damage taken, and the vampire regains Hit Points equal to that amount. A Humanoid reduced to 0 Hit Points by this damage and then buried rises the following sunset as a Vampire Spawn under the vampire's control.",
      },
    ],
    bonusActions: [
      {
        name: "Charm (Recharge 5-6)",
        text: "The vampire casts Charm Person, requiring no spell components and using Charisma as the spellcasting ability (spell save DC 17), and the duration is 24 hours. The Charmed target is a willing recipient of the vampire's Bite, the damage of which doesn't end the spell. When the spell ends, the target is unaware it was Charmed by the vampire.",
      },
      {
        name: "Shape-Shift",
        text: "If the vampire isn't in sunlight or running water, it shape-shifts into a Tiny bat (Speed 5 ft., Fly Speed 30 ft.) or a Medium cloud of mist (Speed 5 ft., Fly Speed 20 ft. [hover]), or it returns to vampire form. Anything it is wearing transforms with it.",
      },
    ],
    legendaryActions: [
      {
        name: "Legendary Action Uses",
        text: "3 (4 in Lair). Immediately after another creature's turn, the vampire can expend a use to take one of its legendary actions. It regains all expended uses at the start of each of its turns.",
      },
      {
        name: "Beguile",
        text: "The vampire casts Command, requiring no spell components and using Charisma as the spellcasting ability (spell save DC 17). The vampire can't take this action again until the start of its next turn.",
      },
      {
        name: "Grave Strike",
        text: "The vampire makes one Grave Strike attack.",
      },
      {
        name: "Move",
        text: "The vampire moves up to half its Speed without provoking Opportunity Attacks.",
      },
    ],
  },

  {
    id: "wight",
    name: "Wight",
    type: "Undead",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 14,
    hp: 82,
    hitDice: "11d8 + 33",
    initiative: { modifier: 4, score: 14 },
    speed: { walk: 30 },
    stats: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    skills: { Perception: 3, Stealth: 4 },
    damageResistances: ["Necrotic"],
    damageImmunities: ["Poison"],
    conditionImmunities: ["Exhaustion", "Poisoned"],
    gear: ["Studded Leather Armor"],
    senses: { darkvision: 60, passivePerception: 13 },
    languages: ["Common", "One other language"],
    challengeRating: "3",
    xp: 700,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Sunlight Sensitivity",
        text: "While in sunlight, the wight has Disadvantage on ability checks and attack rolls.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        text: "The wight makes two attacks, using Necrotic Sword or Necrotic Bow in any combination. It can replace one attack with a use of Life Drain.",
      },
      {
        name: "Necrotic Sword",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 6 (1d8 + 2) Slashing damage plus 4 (1d8) Necrotic damage.",
      },
      {
        name: "Necrotic Bow",
        text: "Ranged Attack Roll: +4, range 150/600 ft. Hit: 6 (1d8 + 2) Piercing damage plus 4 (1d8) Necrotic damage.",
      },
      {
        name: "Life Drain",
        text: "Constitution Saving Throw: DC 13, one creature within 5 feet. Failure: 6 (1d8 + 2) Necrotic damage, and the target's Hit Point maximum decreases by an amount equal to the damage taken. A Humanoid slain by this attack rises 24 hours later as a Zombie under the wight's control unless restored to life or its body is destroyed. The wight can have no more than twelve zombies under its control at a time.",
      },
    ],
  },

  {
    id: "will-o-wisp",
    name: "Will-o'-Wisp",
    type: "Undead",
    size: "Tiny",
    alignment: "Chaotic Evil",
    armorClass: 19,
    hp: 27,
    hitDice: "11d4",
    initiative: { modifier: 9, score: 19 },
    speed: { walk: 5, fly: 50, hover: true },
    stats: { str: 1, dex: 28, con: 10, int: 13, wis: 14, cha: 11 },
    damageResistances: [
      "Acid",
      "Bludgeoning",
      "Cold",
      "Fire",
      "Necrotic",
      "Piercing",
      "Slashing",
    ],
    damageImmunities: ["Lightning", "Poison"],
    conditionImmunities: [
      "Exhaustion",
      "Grappled",
      "Paralyzed",
      "Petrified",
      "Poisoned",
      "Prone",
      "Restrained",
      "Unconscious",
    ],
    senses: { darkvision: 120, passivePerception: 12 },
    languages: ["Common", "One other language"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Ephemeral",
        text: "The wisp can't wear or carry anything.",
      },
      {
        name: "Illumination",
        text: "The wisp sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet.",
      },
      {
        name: "Incorporeal Movement",
        text: "The wisp can move through other creatures and objects as if they were Difficult Terrain. It takes 5 (1d10) Force damage if it ends its turn inside an object.",
      },
    ],
    actions: [
      {
        name: "Shock",
        text: "Melee Attack Roll: +4, reach 5 ft. Hit: 11 (2d8 + 2) Lightning damage.",
      },
    ],
    bonusActions: [
      {
        name: "Consume Life",
        text: "Constitution Saving Throw: DC 10, one living creature the wisp can see within 5 feet that has 0 Hit Points. Failure: The target dies, and the wisp regains 10 (3d6) Hit Points.",
      },
      {
        name: "Vanish",
        text: "The wisp and its light have the Invisible condition until the wisp's Concentration ends on this effect, which ends early immediately after the wisp makes an attack roll or uses Consume Life.",
      },
    ],
  },

  {
    id: "wraith",
    name: "Wraith",
    type: "Undead",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 13,
    hp: 67,
    hitDice: "9d8 + 27",
    initiative: { modifier: 3, score: 13 },
    speed: { walk: 5, fly: 60, hover: true },
    stats: { str: 6, dex: 16, con: 16, int: 12, wis: 14, cha: 15 },
    damageResistances: ["Acid", "Bludgeoning", "Cold", "Fire", "Piercing", "Slashing"],
    damageImmunities: ["Necrotic", "Poison"],
    conditionImmunities: [
      "Charmed",
      "Exhaustion",
      "Grappled",
      "Paralyzed",
      "Petrified",
      "Poisoned",
      "Prone",
      "Restrained",
      "Unconscious",
    ],
    senses: { darkvision: 60, passivePerception: 12 },
    languages: ["Common", "Two other languages"],
    challengeRating: "5",
    xp: 1800,
    proficiencyBonus: 3,
    traits: [
      {
        name: "Incorporeal Movement",
        text: "The wraith can move through other creatures and objects as if they were Difficult Terrain. It takes 5 (1d10) Force damage if it ends its turn inside an object.",
      },
      {
        name: "Sunlight Sensitivity",
        text: "While in sunlight, the wraith has Disadvantage on ability checks and attack rolls.",
      },
    ],
    actions: [
      {
        name: "Life Drain",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 21 (4d8 + 3) Necrotic damage. If the target is a creature, its Hit Point maximum decreases by an amount equal to the damage taken.",
      },
      {
        name: "Create Specter",
        text: "The wraith targets a Humanoid corpse within 10 feet that has been dead for no longer than 1 minute. The target's spirit rises as a Specter in the space of its corpse or the nearest unoccupied space. The specter is under the wraith's control. The wraith can have no more than seven specters under its control at a time.",
      },
    ],
  },

  {
    id: "zombie",
    name: "Zombie",
    type: "Undead",
    size: "Medium",
    alignment: "Neutral Evil",
    armorClass: 8,
    hp: 15,
    hitDice: "2d8 + 6",
    initiative: { modifier: -2, score: 8 },
    speed: { walk: 20 },
    stats: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    savingThrows: { wis: 0 },
    damageImmunities: ["Poison"],
    conditionImmunities: ["Exhaustion", "Poisoned"],
    senses: { darkvision: 60, passivePerception: 8 },
    languages: ["Understands Common plus one other language but can't speak"],
    challengeRating: "1/4",
    xp: 50,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Undead Fortitude",
        text: "If damage reduces the zombie to 0 Hit Points, it makes a Constitution saving throw (DC 5 plus the damage taken) unless the damage is Radiant or from a Critical Hit. On a successful save, the zombie drops to 1 Hit Point instead.",
      },
    ],
    actions: [
      {
        name: "Slam",
        text: "Melee Attack Roll: +3, reach 5 ft. Hit: 5 (1d8 + 1) Bludgeoning damage.",
      },
    ],
  },

  {
    id: "ogre-zombie",
    name: "Ogre Zombie",
    type: "Undead",
    size: "Large",
    alignment: "Neutral Evil",
    armorClass: 8,
    hp: 85,
    hitDice: "9d10 + 36",
    initiative: { modifier: -2, score: 8 },
    speed: { walk: 30 },
    stats: { str: 19, dex: 6, con: 18, int: 3, wis: 6, cha: 5 },
    savingThrows: { wis: 0 },
    damageImmunities: ["Poison"],
    conditionImmunities: ["Exhaustion", "Poisoned"],
    senses: { darkvision: 60, passivePerception: 8 },
    languages: ["Understands Common and Giant but can't speak"],
    challengeRating: "2",
    xp: 450,
    proficiencyBonus: 2,
    traits: [
      {
        name: "Undead Fortitude",
        text: "If damage reduces the zombie to 0 Hit Points, it makes a Constitution saving throw (DC 5 plus the damage taken) unless the damage is Radiant or from a Critical Hit. On a successful save, the zombie drops to 1 Hit Point instead.",
      },
    ],
    actions: [
      {
        name: "Slam",
        text: "Melee Attack Roll: +6, reach 5 ft. Hit: 13 (2d8 + 4) Bludgeoning damage.",
      },
    ],
  },
];
