import type { ToolId } from "./types";

export const toolLabels: Record<ToolId, string> = {
  "alchemists-supplies": "Alchemist’s Supplies",
  "bagpipes": "Bagpipes",
  "brewers-supplies": "Brewer’s Supplies",
  "calligraphers-supplies": "Calligrapher’s Supplies",
  "carpenters-tools": "Carpenter’s Tools",
  "cartographers-tools": "Cartographer’s Tools",
  "cobblers-tools": "Cobbler’s Tools",
  "cooks-utensils": "Cook’s Utensils",
  "disguise-kit": "Disguise Kit",
  "drum": "Drum",
  "dulcimer": "Dulcimer",
  "flute": "Flute",
  "forgery-kit": "Forgery Kit",
  "gaming-set": "Gaming Set",
  "glassblowers-tools": "Glassblower’s Tools",
  "herbalism-kit": "Herbalism Kit",
  "horn": "Horn",
  "jewelers-tools": "Jeweler’s Tools",
  "leatherworkers-tools": "Leatherworker’s Tools",
  "lute": "Lute",
  "lyre": "Lyre",
  "masons-tools": "Mason’s Tools",
  "navigator-tools": "Navigator’s Tools",
  "painters-supplies": "Painter’s Supplies",
  "pan-flute": "Pan Flute",
  "poisoners-kit": "Poisoner’s Kit",
  "potters-tools": "Potter’s Tools",
  "shawm": "Shawm",
  "smiths-tools": "Smith’s Tools",
  "thieves-tools": "Thieves’ Tools",
  "tinkers-tools": "Tinker’s Tools",
  "vehicles-land": "Land Vehicles",
  "vehicles-water": "Water Vehicles",
  "viol": "Viol",
  "weavers-tools": "Weaver’s Tools",
  "woodcarvers-tools": "Woodcarver’s Tools",
};